(cl:in-package nortek_dvl-msg)
(cl:export '(HEADER-VAL
          HEADER
          B1_VEL_VALID-VAL
          B1_VEL_VALID
          B2_VEL_VALID-VAL
          B2_VEL_VALID
          B3_VEL_VALID-VAL
          B3_VEL_VALID
          B4_VEL_VALID-VAL
          B4_VEL_VALID
          B1_DIST_VALID-VAL
          B1_DIST_VALID
          B2_DIST_VALID-VAL
          B2_DIST_VALID
          B3_DIST_VALID-VAL
          B3_DIST_VALID
          B4_DIST_VALID-VAL
          B4_DIST_VALID
          B1_FOM_VALID-VAL
          B1_FOM_VALID
          B2_FOM_VALID-VAL
          B2_FOM_VALID
          B3_FOM_VALID-VAL
          B3_FOM_VALID
          B4_FOM_VALID-VAL
          B4_FOM_VALID
          X_VEL_VALID-VAL
          X_VEL_VALID
          Y_VEL_VALID-VAL
          Y_VEL_VALID
          Z1_VEL_VALID-VAL
          Z1_VEL_VALID
          Z2_VEL_VALID-VAL
          Z2_VEL_VALID
          X_FOM_VALID-VAL
          X_FOM_VALID
          Y_FOM_VALID-VAL
          Y_FOM_VALID
          Z1_FOM_VALID-VAL
          Z1_FOM_VALID
          Z2_FOM_VALID-VAL
          Z2_FOM_VALID
          PROC_CAP-VAL
          PROC_CAP
          WAKEUP_STATE-VAL
          WAKEUP_STATE
))