#!/bin/bash

# A script to install Ceres Solver
#
#   Mostly taken from:
#     http://ceres-solver.org/building.html

# Dependencies

sudo apt-get install -y cmake
sudo apt-get install -y libgoogle-glog-dev
sudo apt-get install -y libatlas-base-dev
sudo apt-get install -y libeigen3-dev
sudo apt-get install -y libsuitesparse-dev

# Download

wget http://ceres-solver.org/ceres-solver-1.11.0.tar.gz

# Install

tar zxf ceres-solver-1.11.0.tar.gz
mkdir ceres-bin
cd ceres-bin
cmake ../ceres-solver-1.11.0
make -j3
make test
# Needed administrative permissions, added sudo.
sudo make install

# Cleanup

cd ..
rm -rf ceres-bin
rm -rf ceres-solver-1.11.0*
