#!/bin/bash

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
wget -q http://packages.ros.org/ros.key -O - | sudo apt-key add -

sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable trusty main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

sudo apt-get -qq -y update
sudo apt-get -qq -y install python-rosdep

sudo rosdep -q -y init
rosdep -q -y update

sudo apt-get -qq -y install ros-indigo-desktop-full ros-indigo-joystick_drivers
sudo apt-get -qq -y remove gazebo2
sudo apt-get -qq -y install ros-indigo-gazebo6-ros-pkgs

echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
