#!/bin/bash

if [ "${ROS_DISTRO:-false}" == "false" ]; then

  if [ $(lsb_release -cs) == "precise" ]; then ROS_DISTRO=hydro
  elif [ $(lsb_release -cs) == "trusty" ]; then ROS_DISTRO=indigo
  elif [ $(lsb_release -cs) == "vivid" ]; then ROS_DISTRO=jade
  else echo "We've had a MAIN B BUS UNDERVOLT."; fi

fi

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -

sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

sudo apt-get -qq update
sudo apt-get -qy install python-rosdep

sudo rosdep -qy init
rosdep -qy update # Do not sudo!

sudo apt-get -qy install ros-indigo-desktop-full ros-indigo-joystick_drivers
sudo apt-get -qy remove gazebo2
sudo apt-get -qy install ros-indigo-gazebo6-ros-pkgs

echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
