#!/bin/bash

# A Script to install only necessary ROS packages
#
#   Installs gazebo6-ros-pkgs
#   Resolves package dependencies

# Select the appropriate ROS version for the current OS:

if [ "${ROS_DISTRO:-false}" == "false" ]; then

  if [ $(lsb_release -cs) == "precise" ]; then ROS_DISTRO=hydro
  elif [ $(lsb_release -cs) == "trusty" ]; then ROS_DISTRO=indigo
  elif [ $(lsb_release -cs) == "vivid" ]; then ROS_DISTRO=jade
  else echo "We've had a MAIN B BUS UNDERVOLT."; fi

fi

# Add the necessary repositories for ROS and Gazebo:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'
wget -nv http://packages.ros.org/ros.key -O - | sudo apt-key add -

sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget -nv http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

# Install rosdep and Gazebo packages:

sudo apt-get -qq update
sudo apt-get -qq -y install python-rosdep ros-"$ROS_DISTRO"-gazebo6-ros-pkgs

sudo rosdep  init
rosdep update # Do not sudo!

# Install the current package's dependencies:

rosdep install -iyq --from-paths ./

echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
