#!/bin/bash

# A script to uninstall ROS, Gazebo and their dependencies.
#
#  Purges all packages beginning with ros-$ROS_DISTRO-.
#  Removes apt repositories and associated keys.
#  Restores .bashrc and removes lingering files.


# Select the appropriate ROS version for the current OS:

if [ "${ROS_DISTRO:-false}" == "false" ]; then

  if [ $(lsb_release -cs) == "precise" ]; then ROS_DISTRO=hydro
  elif [ $(lsb_release -cs) == "trusty" ]; then ROS_DISTRO=indigo
  elif [ $(lsb_release -cs) == "vivid" ]; then ROS_DISTRO=jade
  else echo "We've had a MAIN B BUS UNDERVOLT."; fi

fi

# Remove ROS/Gazebo packages, configs and dependencies:

sudo apt-get -qq -y purge ros-"$ROS_DISTRO"-* gazebo* sixad
sudo apt-get -qq -y autoremove

# Backup .bashrc and create a new version sans ROS:

cp ~/.bashrc ~/.bashrc.bak
grep -v "source \(/opt/ros/[a-z]\+\|.\+/devel\)/setup.bash" ~/.bashrc.bak > ~/.bashrc

# Remove ROS source and key

sudo rm -f /etc/apt/sources.list.d/ros-latest.list
sudo apt-key del B01FA116

# Remove Gazebo source and key

sudo rm -f /etc/apt/sources.list.d/gazebo-stable.list
sudo apt-key del AF249743

# Remove Sixaxis source and key

sudo apt-add-repository -y --remove ppa:falk-t-j/qtsixa
sudo rm -f /etc/apt/sources.list.d/falk-t-j-qtsixa-trusty.list
sudo apt-key del 736E4F0B

# Delete files left by rosdep..?

sudo rm -rf /etc/ros
