# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nortek_dvl/Dvl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Dvl(genpy.Message):
  _md5sum = "b1ec29ea990029dc78359fd83b508011"
  _type = "nortek_dvl/Dvl"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float64 time    #ping time
float64 dt1     #time from trigger to center of water track cell
float64 dt2     #time from start of output message to center of water track cell
geometry_msgs/Vector3 velocity
float64 figureOfMerit
float64[4] beamDistance
float64 batteryVoltage
float64 speedSound
float64 pressure
float64 temp
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','time','dt1','dt2','velocity','figureOfMerit','beamDistance','batteryVoltage','speedSound','pressure','temp']
  _slot_types = ['std_msgs/Header','float64','float64','float64','geometry_msgs/Vector3','float64','float64[4]','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,time,dt1,dt2,velocity,figureOfMerit,beamDistance,batteryVoltage,speedSound,pressure,temp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Dvl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.time is None:
        self.time = 0.
      if self.dt1 is None:
        self.dt1 = 0.
      if self.dt2 is None:
        self.dt2 = 0.
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.figureOfMerit is None:
        self.figureOfMerit = 0.
      if self.beamDistance is None:
        self.beamDistance = [0.] * 4
      if self.batteryVoltage is None:
        self.batteryVoltage = 0.
      if self.speedSound is None:
        self.speedSound = 0.
      if self.pressure is None:
        self.pressure = 0.
      if self.temp is None:
        self.temp = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.time = 0.
      self.dt1 = 0.
      self.dt2 = 0.
      self.velocity = geometry_msgs.msg.Vector3()
      self.figureOfMerit = 0.
      self.beamDistance = [0.] * 4
      self.batteryVoltage = 0.
      self.speedSound = 0.
      self.pressure = 0.
      self.temp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.time, _x.dt1, _x.dt2, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.figureOfMerit))
      buff.write(_get_struct_4d().pack(*self.beamDistance))
      _x = self
      buff.write(_get_struct_4d().pack(_x.batteryVoltage, _x.speedSound, _x.pressure, _x.temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.time, _x.dt1, _x.dt2, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.figureOfMerit,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 32
      self.beamDistance = _get_struct_4d().unpack(str[start:end])
      _x = self
      start = end
      end += 32
      (_x.batteryVoltage, _x.speedSound, _x.pressure, _x.temp,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.time, _x.dt1, _x.dt2, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.figureOfMerit))
      buff.write(self.beamDistance.tostring())
      _x = self
      buff.write(_get_struct_4d().pack(_x.batteryVoltage, _x.speedSound, _x.pressure, _x.temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.time, _x.dt1, _x.dt2, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.figureOfMerit,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 32
      self.beamDistance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      _x = self
      start = end
      end += 32
      (_x.batteryVoltage, _x.speedSound, _x.pressure, _x.temp,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
