// Generated by gencpp from file imu_3dm_gx4/FilterOutput.msg
// DO NOT EDIT!


#ifndef IMU_3DM_GX4_MESSAGE_FILTEROUTPUT_H
#define IMU_3DM_GX4_MESSAGE_FILTEROUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace imu_3dm_gx4
{
template <class ContainerAllocator>
struct FilterOutput_
{
  typedef FilterOutput_<ContainerAllocator> Type;

  FilterOutput_()
    : header()
    , quaternion()
    , quaternion_status(0)
    , euler_rpy()
    , euler_rpy_status(0.0)
    , euler_angle_covariance()
    , euler_angle_covariance_status(0)
    , heading_update_alt(0.0)
    , heading_update_LORD(0.0)
    , heading_update_uncertainty(0.0)
    , heading_update_source(0.0)
    , heading_update_flags(0.0)
    , gyro_bias()
    , gyro_bias_status(0)
    , gyro_bias_covariance()
    , gyro_bias_covariance_status(0)
    , linear_acceleration()
    , linear_acceleration_status(0.0)
    , angular_velocity()
    , angular_velocity_status(0.0)  {
      euler_angle_covariance.assign(0.0);

      gyro_bias_covariance.assign(0.0);
  }
  FilterOutput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , quaternion(_alloc)
    , quaternion_status(0)
    , euler_rpy(_alloc)
    , euler_rpy_status(0.0)
    , euler_angle_covariance()
    , euler_angle_covariance_status(0)
    , heading_update_alt(0.0)
    , heading_update_LORD(0.0)
    , heading_update_uncertainty(0.0)
    , heading_update_source(0.0)
    , heading_update_flags(0.0)
    , gyro_bias(_alloc)
    , gyro_bias_status(0)
    , gyro_bias_covariance()
    , gyro_bias_covariance_status(0)
    , linear_acceleration(_alloc)
    , linear_acceleration_status(0.0)
    , angular_velocity(_alloc)
    , angular_velocity_status(0.0)  {
  (void)_alloc;
      euler_angle_covariance.assign(0.0);

      gyro_bias_covariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _quaternion_type;
  _quaternion_type quaternion;

   typedef uint16_t _quaternion_status_type;
  _quaternion_status_type quaternion_status;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _euler_rpy_type;
  _euler_rpy_type euler_rpy;

   typedef double _euler_rpy_status_type;
  _euler_rpy_status_type euler_rpy_status;

   typedef boost::array<double, 9>  _euler_angle_covariance_type;
  _euler_angle_covariance_type euler_angle_covariance;

   typedef uint16_t _euler_angle_covariance_status_type;
  _euler_angle_covariance_status_type euler_angle_covariance_status;

   typedef double _heading_update_alt_type;
  _heading_update_alt_type heading_update_alt;

   typedef double _heading_update_LORD_type;
  _heading_update_LORD_type heading_update_LORD;

   typedef double _heading_update_uncertainty_type;
  _heading_update_uncertainty_type heading_update_uncertainty;

   typedef double _heading_update_source_type;
  _heading_update_source_type heading_update_source;

   typedef double _heading_update_flags_type;
  _heading_update_flags_type heading_update_flags;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _gyro_bias_type;
  _gyro_bias_type gyro_bias;

   typedef uint16_t _gyro_bias_status_type;
  _gyro_bias_status_type gyro_bias_status;

   typedef boost::array<double, 9>  _gyro_bias_covariance_type;
  _gyro_bias_covariance_type gyro_bias_covariance;

   typedef uint16_t _gyro_bias_covariance_status_type;
  _gyro_bias_covariance_status_type gyro_bias_covariance_status;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef double _linear_acceleration_status_type;
  _linear_acceleration_status_type linear_acceleration_status;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef double _angular_velocity_status_type;
  _angular_velocity_status_type angular_velocity_status;



  enum {
    STATUS_INVALID = 0u,
    STATUS_VALID = 1u,
    STATUS_VALID_REFERENCED = 2u,
  };


  typedef boost::shared_ptr< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> const> ConstPtr;

}; // struct FilterOutput_

typedef ::imu_3dm_gx4::FilterOutput_<std::allocator<void> > FilterOutput;

typedef boost::shared_ptr< ::imu_3dm_gx4::FilterOutput > FilterOutputPtr;
typedef boost::shared_ptr< ::imu_3dm_gx4::FilterOutput const> FilterOutputConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_3dm_gx4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'imu_3dm_gx4': ['/home/pparekh/osu-uwrt/riptide_software/src/riptide_utilities/setup_scripts/dependencies/src/imu_3dm_gx4/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ebeb70bfcf2c275d32570ff4a241bad";
  }

  static const char* value(const ::imu_3dm_gx4::FilterOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ebeb70bfcf2c275ULL;
  static const uint64_t static_value2 = 0xd32570ff4a241badULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_3dm_gx4/FilterOutput";
  }

  static const char* value(const ::imu_3dm_gx4::FilterOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Output from the 3DM-GX4 attitude estimation filter.\n\
\n\
# Note on status flags:\n\
# Status flags are implemented as bit-fields.\n\
#  0 = invalid\n\
#  1 = valid\n\
#  2 = valid and referenced to magnetic north\n\
#\n\
# Note that covariance on orientation becomes invalid as pitch angle exceeds 70 # degrees. \n\
# This will be indicated by the status flag.\n\
\n\
std_msgs/Header header\n\
\n\
# Quaternion, and status\n\
geometry_msgs/Quaternion quaternion\n\
uint16 quaternion_status\n\
\n\
# Gyroscope Euler angles roll, pitch, yaw, and status\n\
geometry_msgs/Vector3 euler_rpy #Roll, Pitch, and Yaw in [radians]\n\
float64 euler_rpy_status\n\
float64[9] euler_angle_covariance\n\
uint16 euler_angle_covariance_status\n\
\n\
# Heading Update Data\n\
float64 heading_update_alt #Heading in [radians]\n\
float64 heading_update_LORD #Heading in [radians]\n\
float64 heading_update_uncertainty #1-sigma heading uncertainty\n\
float64 heading_update_source\n\
float64 heading_update_flags #0 = no update received within 2 sec, 1 = update received within 2 sec\n\
\n\
# Gyro bias, diagonal covariance, and status\n\
geometry_msgs/Vector3 gyro_bias #Gyro bias from sensor frame [radians/sec]\n\
uint16 gyro_bias_status\n\
float64[9] gyro_bias_covariance\n\
uint16 gyro_bias_covariance_status\n\
\n\
# Linear accelerations along x,y,z axes, and status\n\
geometry_msgs/Vector3 linear_acceleration #X, Y, and Z axes in [m/s^2]\n\
float64 linear_acceleration_status\n\
\n\
# Angular rates along x,y,z axes, and status\n\
geometry_msgs/Vector3 angular_velocity #X, Y, and Z axes in [radians/s]\n\
float64 angular_velocity_status\n\
\n\
# Constants\n\
uint16 STATUS_INVALID = 0\n\
uint16 STATUS_VALID = 1\n\
uint16 STATUS_VALID_REFERENCED = 2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::imu_3dm_gx4::FilterOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.quaternion);
      stream.next(m.quaternion_status);
      stream.next(m.euler_rpy);
      stream.next(m.euler_rpy_status);
      stream.next(m.euler_angle_covariance);
      stream.next(m.euler_angle_covariance_status);
      stream.next(m.heading_update_alt);
      stream.next(m.heading_update_LORD);
      stream.next(m.heading_update_uncertainty);
      stream.next(m.heading_update_source);
      stream.next(m.heading_update_flags);
      stream.next(m.gyro_bias);
      stream.next(m.gyro_bias_status);
      stream.next(m.gyro_bias_covariance);
      stream.next(m.gyro_bias_covariance_status);
      stream.next(m.linear_acceleration);
      stream.next(m.linear_acceleration_status);
      stream.next(m.angular_velocity);
      stream.next(m.angular_velocity_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FilterOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_3dm_gx4::FilterOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_3dm_gx4::FilterOutput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "quaternion: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quaternion);
    s << indent << "quaternion_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.quaternion_status);
    s << indent << "euler_rpy: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.euler_rpy);
    s << indent << "euler_rpy_status: ";
    Printer<double>::stream(s, indent + "  ", v.euler_rpy_status);
    s << indent << "euler_angle_covariance[]" << std::endl;
    for (size_t i = 0; i < v.euler_angle_covariance.size(); ++i)
    {
      s << indent << "  euler_angle_covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.euler_angle_covariance[i]);
    }
    s << indent << "euler_angle_covariance_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.euler_angle_covariance_status);
    s << indent << "heading_update_alt: ";
    Printer<double>::stream(s, indent + "  ", v.heading_update_alt);
    s << indent << "heading_update_LORD: ";
    Printer<double>::stream(s, indent + "  ", v.heading_update_LORD);
    s << indent << "heading_update_uncertainty: ";
    Printer<double>::stream(s, indent + "  ", v.heading_update_uncertainty);
    s << indent << "heading_update_source: ";
    Printer<double>::stream(s, indent + "  ", v.heading_update_source);
    s << indent << "heading_update_flags: ";
    Printer<double>::stream(s, indent + "  ", v.heading_update_flags);
    s << indent << "gyro_bias: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.gyro_bias);
    s << indent << "gyro_bias_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.gyro_bias_status);
    s << indent << "gyro_bias_covariance[]" << std::endl;
    for (size_t i = 0; i < v.gyro_bias_covariance.size(); ++i)
    {
      s << indent << "  gyro_bias_covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gyro_bias_covariance[i]);
    }
    s << indent << "gyro_bias_covariance_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.gyro_bias_covariance_status);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "linear_acceleration_status: ";
    Printer<double>::stream(s, indent + "  ", v.linear_acceleration_status);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "angular_velocity_status: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_3DM_GX4_MESSAGE_FILTEROUTPUT_H
