// Generated by gencpp from file imu_3dm_gx4/MagFieldCF.msg
// DO NOT EDIT!


#ifndef IMU_3DM_GX4_MESSAGE_MAGFIELDCF_H
#define IMU_3DM_GX4_MESSAGE_MAGFIELDCF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace imu_3dm_gx4
{
template <class ContainerAllocator>
struct MagFieldCF_
{
  typedef MagFieldCF_<ContainerAllocator> Type;

  MagFieldCF_()
    : header()
    , components()
    , magnitude(0.0)
    , covariance()  {
      covariance.assign(0.0);
  }
  MagFieldCF_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , components(_alloc)
    , magnitude(0.0)
    , covariance()  {
  (void)_alloc;
      covariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _components_type;
  _components_type components;

   typedef double _magnitude_type;
  _magnitude_type magnitude;

   typedef boost::array<double, 9>  _covariance_type;
  _covariance_type covariance;





  typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> const> ConstPtr;

}; // struct MagFieldCF_

typedef ::imu_3dm_gx4::MagFieldCF_<std::allocator<void> > MagFieldCF;

typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldCF > MagFieldCFPtr;
typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldCF const> MagFieldCFConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_3dm_gx4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'imu_3dm_gx4': ['/home/pparekh/osu-uwrt/riptide_software/src/riptide_utilities/setup_scripts/dependencies/src/imu_3dm_gx4/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd32a4ab24c73ea547c18eb391466a22";
  }

  static const char* value(const ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd32a4ab24c73ea5ULL;
  static const uint64_t static_value2 = 0x47c18eb391466a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_3dm_gx4/MagFieldCF";
  }

  static const char* value(const ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Magnetic Field Message - Complimentary Filter\n\
std_msgs/Header header\n\
geometry_msgs/Vector3 components # X, Y, Z components [Gauss]\n\
float64 magnitude # Total magnitude [Gauss]\n\
float64[9] covariance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.components);
      stream.next(m.magnitude);
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagFieldCF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_3dm_gx4::MagFieldCF_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "components: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.components);
    s << indent << "magnitude: ";
    Printer<double>::stream(s, indent + "  ", v.magnitude);
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_3DM_GX4_MESSAGE_MAGFIELDCF_H
