// Generated by gencpp from file imu_3dm_gx4/MagFieldKF.msg
// DO NOT EDIT!


#ifndef IMU_3DM_GX4_MESSAGE_MAGFIELDKF_H
#define IMU_3DM_GX4_MESSAGE_MAGFIELDKF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace imu_3dm_gx4
{
template <class ContainerAllocator>
struct MagFieldKF_
{
  typedef MagFieldKF_<ContainerAllocator> Type;

  MagFieldKF_()
    : header()
    , mag_field_N(0.0)
    , mag_field_E(0.0)
    , mag_field_D(0.0)
    , mag_field_magnitude(0.0)
    , inclination(0.0)
    , declination(0.0)
    , mag_status(0)  {
    }
  MagFieldKF_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mag_field_N(0.0)
    , mag_field_E(0.0)
    , mag_field_D(0.0)
    , mag_field_magnitude(0.0)
    , inclination(0.0)
    , declination(0.0)
    , mag_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _mag_field_N_type;
  _mag_field_N_type mag_field_N;

   typedef double _mag_field_E_type;
  _mag_field_E_type mag_field_E;

   typedef double _mag_field_D_type;
  _mag_field_D_type mag_field_D;

   typedef double _mag_field_magnitude_type;
  _mag_field_magnitude_type mag_field_magnitude;

   typedef double _inclination_type;
  _inclination_type inclination;

   typedef double _declination_type;
  _declination_type declination;

   typedef uint16_t _mag_status_type;
  _mag_status_type mag_status;





  typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> const> ConstPtr;

}; // struct MagFieldKF_

typedef ::imu_3dm_gx4::MagFieldKF_<std::allocator<void> > MagFieldKF;

typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldKF > MagFieldKFPtr;
typedef boost::shared_ptr< ::imu_3dm_gx4::MagFieldKF const> MagFieldKFConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_3dm_gx4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'imu_3dm_gx4': ['/home/pparekh/osu-uwrt/riptide_software/src/riptide_utilities/setup_scripts/dependencies/src/imu_3dm_gx4/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80d2cbcb915a78650f5f0199105cb92b";
  }

  static const char* value(const ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80d2cbcb915a7865ULL;
  static const uint64_t static_value2 = 0x0f5f0199105cb92bULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_3dm_gx4/MagFieldKF";
  }

  static const char* value(const ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Magnetic Field Message - Estimation Kalman Filter\n\
std_msgs/Header header\n\
float64 mag_field_N # Gauss\n\
float64 mag_field_E # Gauss\n\
float64 mag_field_D # Gauss\n\
float64 mag_field_magnitude # Gauss\n\
float64 inclination # Degrees\n\
float64 declination # Degrees\n\
uint16 mag_status # 0 = invalid, 1 = valid\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mag_field_N);
      stream.next(m.mag_field_E);
      stream.next(m.mag_field_D);
      stream.next(m.mag_field_magnitude);
      stream.next(m.inclination);
      stream.next(m.declination);
      stream.next(m.mag_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagFieldKF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_3dm_gx4::MagFieldKF_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mag_field_N: ";
    Printer<double>::stream(s, indent + "  ", v.mag_field_N);
    s << indent << "mag_field_E: ";
    Printer<double>::stream(s, indent + "  ", v.mag_field_E);
    s << indent << "mag_field_D: ";
    Printer<double>::stream(s, indent + "  ", v.mag_field_D);
    s << indent << "mag_field_magnitude: ";
    Printer<double>::stream(s, indent + "  ", v.mag_field_magnitude);
    s << indent << "inclination: ";
    Printer<double>::stream(s, indent + "  ", v.inclination);
    s << indent << "declination: ";
    Printer<double>::stream(s, indent + "  ", v.declination);
    s << indent << "mag_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.mag_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_3DM_GX4_MESSAGE_MAGFIELDKF_H
