#!/bin/bash

rosrun camera_calibration cameracalibrator.py -p chessboard -s 8x6 -q 0.042 right:=/stereo/right/image_raw left:=/stereo/left/image_raw left_camera:=/stereo/left right_camera:=/stereo/right --approximate 0.05
