#!/bin/bash

echo -e "\nRunning...\n    rosrun xacro xacro riptide.urdf.xacro > riptide.urdf"
rosrun xacro xacro riptide.xacro > riptide.urdf || exit
echo -e "Build complete\n"

echo -e "Running...\n    check_urdf riptide.urdf"
check_urdf riptide.urdf > /dev/null || exit
echo -e "Check complete\n"

echo -e "Running...\n    gz sdf -k riptide.urdf"
gz sdf -k riptide.urdf || exit

echo -e "\nRunning...\n    gz sdf -p riptide.urdf > riptide.sdf"
gz sdf -p riptide.urdf > riptide.sdf || exit
echo -e "File generated"

echo -e "\nRobot ready\n"
