# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu_3dm_gx4/MagFieldKF.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MagFieldKF(genpy.Message):
  _md5sum = "80d2cbcb915a78650f5f0199105cb92b"
  _type = "imu_3dm_gx4/MagFieldKF"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """#Magnetic Field Message - Estimation Kalman Filter
std_msgs/Header header
float64 mag_field_N # Gauss
float64 mag_field_E # Gauss
float64 mag_field_D # Gauss
float64 mag_field_magnitude # Gauss
float64 inclination # Degrees
float64 declination # Degrees
uint16 mag_status # 0 = invalid, 1 = valid

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','mag_field_N','mag_field_E','mag_field_D','mag_field_magnitude','inclination','declination','mag_status']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mag_field_N,mag_field_E,mag_field_D,mag_field_magnitude,inclination,declination,mag_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MagFieldKF, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mag_field_N is None:
        self.mag_field_N = 0.
      if self.mag_field_E is None:
        self.mag_field_E = 0.
      if self.mag_field_D is None:
        self.mag_field_D = 0.
      if self.mag_field_magnitude is None:
        self.mag_field_magnitude = 0.
      if self.inclination is None:
        self.inclination = 0.
      if self.declination is None:
        self.declination = 0.
      if self.mag_status is None:
        self.mag_status = 0
    else:
      self.header = std_msgs.msg.Header()
      self.mag_field_N = 0.
      self.mag_field_E = 0.
      self.mag_field_D = 0.
      self.mag_field_magnitude = 0.
      self.inclination = 0.
      self.declination = 0.
      self.mag_status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6dH().pack(_x.mag_field_N, _x.mag_field_E, _x.mag_field_D, _x.mag_field_magnitude, _x.inclination, _x.declination, _x.mag_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 50
      (_x.mag_field_N, _x.mag_field_E, _x.mag_field_D, _x.mag_field_magnitude, _x.inclination, _x.declination, _x.mag_status,) = _get_struct_6dH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6dH().pack(_x.mag_field_N, _x.mag_field_E, _x.mag_field_D, _x.mag_field_magnitude, _x.inclination, _x.declination, _x.mag_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 50
      (_x.mag_field_N, _x.mag_field_E, _x.mag_field_D, _x.mag_field_magnitude, _x.inclination, _x.declination, _x.mag_status,) = _get_struct_6dH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6dH = None
def _get_struct_6dH():
    global _struct_6dH
    if _struct_6dH is None:
        _struct_6dH = struct.Struct("<6dH")
    return _struct_6dH
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
