#!/bin/bash

# Example workspace creation:

mkdir -p ~/osu-uwrt/riptide_ws/src
cd ~/osu-uwrt/riptide_ws/src
catkin_init_workspace

cd ~/osu-uwrt/riptide_ws
catkin_make

echo "source ~/osu-uwrt/riptide_ws/devel/setup.bash" >> ~/.bashrc
