#!/bin/bash

# Catkin Workspace Setup Example

echo "Creating workspace..."
mkdir -p ~/osu-uwrt/riptide_ws/src
cd ~/osu-uwrt/riptide_ws/src
catkin_init_workspace

echo "Compiling workspace..."
cd ~/osu-uwrt/riptide_ws
catkin_make

echo "Installing workspace..."
echo "source ~/osu-uwrt/riptide_ws/devel/setup.bash" >> ~/.bashrc
