#!/bin/bash


# A script to install ROS Desktop Full.
#
#   Installs ros-$ROS_DISTRO-desktop-full
#   without the option for buoyancy simulation.
#
#   Installs a manually updated list of
#   Riptide's dependencies using apt.
#
#   Also installed, are other packages from the Ubuntu
#   and Sixaxis repositories to enable system development.


# Select the appropriate version of ROS for the current OS:

if [ "${ROS_DISTRO:-false}" == "false" ]; then

  if [ "$(lsb_release -cs)" == "precise" ]; then ROS_DISTRO=hydro
  elif [ "$(lsb_release -cs)" == "trusty" ]; then ROS_DISTRO=indigo
  elif [ "$(lsb_release -cs)" == "vivid" ]; then ROS_DISTRO=jade
  else echo "We've had a MAIN B BUS UNDERVOLT."; fi

fi


# Send and notification of what is being installed to std out:

distro="$ROS_DISTRO"
distro="$(tr '[:lower:]' '[:upper:]' <<< ${distro:0:1})${distro:1}"
release="$(lsb_release -cs)"
release="$(tr '[:lower:]' '[:upper:]' <<< ${release:0:1})${release:1}"
echo -e "\nInstalling ROS $distro on Ubuntu $release.\n"


# Add ROS repository, ROS key and Sixaxis repository:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -

sudo apt-add-repository -y ppa:falk-t-j/qtsixa


# Update repositories to reflect the preceding additions:

sudo apt-get update


# Install Ubuntu and Sixaxis packages:

sudo apt-get -y install git openssh-server joystick
sudo apt-get -y install sixad


# Install ROS Desktop Full:

sudo apt-get -y install ros-"$ROS_DISTRO"-desktop-full


# Requirements not found in "(most of) ROS Desktop Full":

# Description:
sudo apt-get -y install liburdfdom-tools
# Estimation
sudo apt-get -y install ros-"$ROS_DISTRO"-robot-localization
# Vision
sudo apt-get -y install ros-"$ROS_DISTRO"-pointgrey-camera-driver


# Prepare rosdep for future use:

sudo rosdep -y init
rosdep -y update # Do not sudo!


# Automatically source ROS from now on:

echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc


# Let the user know how to make the current terminal work:

echo -e "\nRun \`source ~/.bashrc\` to update the current shell.\n"
