#!/bin/bash

# ------------------------------ #
#  Install Sphinx Doc Generator  #
# ------------------------------ #


# Having already run `./scripts/install-ros`


# Install Sphinx and the RTD theme:
if [ "$TRAVIS" != true ]; then
   sudo pip install -q sphinx
   sudo pip install -q sphinx_rtd_theme
   # Build the docs for the humans:
   cd ~/osu-uwrt/riptide_ws/src/docs/
   make html
   echo "The documentation is now accessible at:"
   echoe "~/osu-uwrt/riptide_ws/src/docs/build/html/index.html"
else
   pip install -q --user travis-sphinx
   pip install -q --user sphinx_rtd_theme
fi
