#!/bin/bash


# A script to install ROS (~desktop-full) with Gazebo 6.
#
#   Installs the gazebo6-ros-pkgs and gazebo6-ros-control
#   packages from the OSRF repository.
#
#   Installs the perception, robot and viz packages from
#   the ROS repository (to provide ~desktop-full functionality).
#
#   Also installed, are other packages from the Ubuntu
#   and Sixaxis repositories to enable system development.


# Select the appropriate version ROS for the current OS:

if [ "${ROS_DISTRO:-false}" == "false" ]; then

  if [ "$(lsb_release -cs)" == "precise" ]; then ROS_DISTRO=hydro
  elif [ "$(lsb_release -cs)" == "trusty" ]; then ROS_DISTRO=indigo
  elif [ "$(lsb_release -cs)" == "vivid" ]; then ROS_DISTRO=jade
  else echo "We've had a MAIN B BUS UNDERVOLT."; fi

fi


# Send and notification of what is being installed to std out:

distro="$ROS_DISTRO"
distro="$(tr '[:lower:]' '[:upper:]' <<< ${distro:0:1})${distro:1}"
release="$(lsb_release -cs)"
release="$(tr '[:lower:]' '[:upper:]' <<< ${release:0:1})${release:1}"
echo -e "\nInstalling ROS $distro on Ubuntu $release.\n"


# Add ROS, Gazebo and Sixaxis repositories and keys:

echo -n "Adding ROS repository..."
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'
wget -nv http://packages.ros.org/ros.key -O - | sudo apt-key add -
echo -e "...done.\n"

echo -n "Adding Gazebo 6 repository..."
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget -nv http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
echo -e "...done.\n"

echo "Adding Sixaxis repository..."
sudo apt-add-repository -y ppa:falk-t-j/qtsixa
echo -e "...done.\n"


# Update repositories to reflect the preceding additions:

echo "Updating package lists..."
sudo apt-get -qq update
echo -e "...done.\n"


# Install Ubuntu and Sixaxis packages:

echo -e "Installing Ubuntu packages...\n"
sudo apt-get -yqq install git openssh-server joystick
echo -e "...done.\n"

echo -e "Installing Sixaxis package...\n"
sudo apt-get -yqq install sixad
echo -e "...done.\n"


# Install (most of) ROS Desktop Full (sans tutorials):

echo -e "Installing Gazebo 6 packages...\n"
sudo apt-get -yqq install ros-"$ROS_DISTRO"-gazebo6-ros-pkgs
sudo apt-get -yqq install ros-"$ROS_DISTRO"-gazebo6-ros-control
echo -e "...done.\n"

echo -e "Installing ROS packages...\n"
sudo apt-get -yqq install ros-"$ROS_DISTRO"-perception
sudo apt-get -yqq install ros-"$ROS_DISTRO"-robot
sudo apt-get -yqq install ros-"$ROS_DISTRO"-viz
echo -e "...done.\n"


# Requirements not found in "(most of) ROS Desktop Full":

echo -e "Initializing and updating rosdep...\n"
sudo rosdep -yq init
rosdep -yq update # Do not sudo!
echo -e "...done.\n"

echo -e "Installing ROS dependencies...\n"
rosdep install -yqi --rosdistro="$ROS_DISTRO" --from-paths ./
echo -e "...done.\n"


# Automatically source ROS from now on:

echo "Adding ROS to ~/.bashrc..."
echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
echo -e "...done.\n"


# Donezo!

echo -e "Installation complete.\n"


# Let the user know how to make the current terminal work:

echo -e "\nRun \`source ~/.bashrc\` to update the current shell.\n"
