#!/bin/bash

# A script to install Ceres Solver
#
#   Mostly taken from:
#     http://ceres-solver.org/building.html

# Dependencies

sudo apt-get install -qy cmake
sudo apt-get install -qy libgoogle-glog-dev
sudo apt-get install -qy libatlas-base-dev
sudo apt-get install -qy libeigen3-dev
sudo apt-get install -qy libsuitesparse-dev

# Download

wget http://ceres-solver.org/ceres-solver-1.11.0.tar.gz

# Install

tar zxf ceres-solver-1.11.0.tar.gz
mkdir ceres-bin
cd ceres-bin || exit
cmake ../ceres-solver-1.11.0
make -j3
if [ "$TRAVIS" != true ]; then
   make test
fi
sudo make install

# Cleanup

cd ..
rm -rf ceres-bin
rm -rf ceres-solver-1.11.0*
