#!/bin/bash

if [ "$TRAVIS" != true ]; then
   sudo pip install -q sphinx
   sudo pip install -q sphinx_rtd_theme
else
   pip install -q --user travis-sphinx
   pip install -q --user sphinx_rtd_theme
fi

