#!/bin/bash

# A script to install Ceres Solver
#
#   Mostly taken from:
#     http://ceres-solver.org/building.html

# Dependencies

sudo apt-get install -yqq cmake
sudo apt-get install -yqq libgoogle-glog-dev
sudo apt-get install -yqq libatlas-base-dev
sudo apt-get install -yqq libeigen3-dev
sudo apt-get install -yqq libsuitesparse-dev

# Download

wget -nv http://ceres-solver.org/ceres-solver-1.11.0.tar.gz

# Install

tar zxf ceres-solver-1.11.0.tar.gz
mkdir ceres-bin
cd ceres-bin || exit
cmake ../ceres-solver-1.11.0
make -s -j3
if [ "$TRAVIS" != true ]; then
   make -s test
fi
sudo make -s install

# Cleanup

cd ..
rm -rf ceres-bin
rm -rf ceres-solver-1.11.0*
