#!/bin/bash

# A script to install ALL of the ROS.
#
#   Installs ros-$ROS_DISTRO-desktop-full.
#   Then installs Riptide dependencies.

# Select the appropriate ROS version for the current OS:

if [ "${ROS_DISTRO:-false}" == "false" ]; then

  if [ $(lsb_release -cs) == "precise" ]; then ROS_DISTRO=hydro
  elif [ $(lsb_release -cs) == "trusty" ]; then ROS_DISTRO=indigo
  elif [ $(lsb_release -cs) == "vivid" ]; then ROS_DISTRO=jade
  else echo "We've had a MAIN B BUS UNDERVOLT."; fi

fi

# Add the necessary repositories for ROS and the PS3 controller:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -

sudo apt-add-repository -y ppa:falk-t-j/qtsixa

# Install packages external to ROS:

sudo apt-get -qq update
sudo apt-get -yqq install arduino openssh-server
sudo apt-get -yqq install sixad joystick
sudo apt-get -yqq install python-rosdep

sudo rosdep -yq init
rosdep -yq update # Do not sudo!

# Install the ROS packages and their dependencies:

sudo apt-get -yqq install ros-"$ROS_DISTRO"-desktop-full
# Autonomy:
sudo apt-get -yqq install ros-"$ROS_DISTRO"-smach
# Description:
sudo apt-get -yqq install liburdfdom-tools
# Estimation
sudo apt-get -yqq install ros-"$ROS_DISTRO"-robot-localization
# Navigation:
sudo apt-get -yqq install ros-"$ROS_DISTRO"-control-toolbox
# Teleop:
sudo apt-get -yqq install ros-"$ROS_DISTRO"-joystick-drivers
# Vision
sudo apt-get -yqq install ros-"$ROS_DISTRO"-camera-calibration
sudo apt-get -yqq install ros-"$ROS_DISTRO"-cv-bridge
sudo apt-get -yqq install ros-"$ROS_DISTRO"-pointgrey-camera-driver

echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
