#!/bin/bash

# --------------------------- #
#  Prepare catkin workspace.  #
# --------------------------- #


# Having just run `git clone ...`


# Create an empty worksapce:
mkdir -p ~/osu-uwrt/riptide_ws/

# Copy the repository to the workspace:
cp -rf ../riptide-ros ~/osu-uwrt/riptide_ws/src

# List the contentents of the destination:
ls -al ~/osu-uwrt/riptide_ws/src

# The original copy of the repo can be deleted:
if [ "$TRAVIS" != true ]; then
   echo "This copy of the repository can now be removed."
fi
