#!/bin/bash

# --------------------------- #
#  Set up a Catkin Workspace  #
# --------------------------- #


# Having already run `./scripts/install-ros`


# Change directories to the workspace:
cd ~/osu-uwrt/riptide_ws

# Build the workspace:
catkin_make

# Make the built packages available for use:
echo "source ~/osu-uwrt/riptide_ws/devel/setup.bash" >> ~/.bashrc
echo -e "Run \`source ~/.bashrc\` to update the current shell."
