#!/bin/bash

# ------------------------------- #
#  Makes PGR cameras accessible.  #
# ------------------------------- #


# Check for super powers:
if [ $UID == 0 ]; then
  # Create the group:
  groupadd pgrimaging
  # Add the user:
  adduser "$SUDO_USER" pgrimaging
  # Find the rules:
  cd ~/osu-uwrt/riptide_ws/src/riptide_vision/udev
  # Add the rules:
  cp pgr.rules /etc/udev/rules.d/
else
  echo "Please try again using sudo."
fi

# Remind the user to reconnect the camera
# and run sudo service udev restart.
echo "Restart udev and replug the camera."
