# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ok', [dirname(__file__)])
        except ImportError:
            import _ok
            return _ok
        if fp is not None:
            try:
                _mod = imp.load_module('_ok', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ok = swig_import_helper()
    del swig_import_helper
else:
    import _ok
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


OK_MAX_DEVICEID_LENGTH = _ok.OK_MAX_DEVICEID_LENGTH
OK_MAX_SERIALNUMBER_LENGTH = _ok.OK_MAX_SERIALNUMBER_LENGTH
OK_MAX_PRODUCT_NAME_LENGTH = _ok.OK_MAX_PRODUCT_NAME_LENGTH
OK_USBSPEED_UNKNOWN = _ok.OK_USBSPEED_UNKNOWN
OK_USBSPEED_FULL = _ok.OK_USBSPEED_FULL
OK_USBSPEED_HIGH = _ok.OK_USBSPEED_HIGH
OK_USBSPEED_SUPER = _ok.OK_USBSPEED_SUPER
okUSBSPEED_UNKNOWN = _ok.okUSBSPEED_UNKNOWN
okUSBSPEED_FULL = _ok.okUSBSPEED_FULL
okUSBSPEED_HIGH = _ok.okUSBSPEED_HIGH
okUSBSPEED_SUPER = _ok.okUSBSPEED_SUPER
OK_INTERFACE_UNKNOWN = _ok.OK_INTERFACE_UNKNOWN
OK_INTERFACE_USB2 = _ok.OK_INTERFACE_USB2
OK_INTERFACE_PCIE = _ok.OK_INTERFACE_PCIE
OK_INTERFACE_USB3 = _ok.OK_INTERFACE_USB3
okDEVICEINTERFACE_UNKNOWN = _ok.okDEVICEINTERFACE_UNKNOWN
okDEVICEINTERFACE_USB2 = _ok.okDEVICEINTERFACE_USB2
okDEVICEINTERFACE_PCIE = _ok.okDEVICEINTERFACE_PCIE
okDEVICEINTERFACE_USB3 = _ok.okDEVICEINTERFACE_USB3
okDEVICESENSOR_INVALID = _ok.okDEVICESENSOR_INVALID
okDEVICESENSOR_BOOL = _ok.okDEVICESENSOR_BOOL
okDEVICESENSOR_INTEGER = _ok.okDEVICESENSOR_INTEGER
okDEVICESENSOR_FLOAT = _ok.okDEVICESENSOR_FLOAT
okDEVICESENSOR_VOLTAGE = _ok.okDEVICESENSOR_VOLTAGE
okDEVICESENSOR_CURRENT = _ok.okDEVICESENSOR_CURRENT
okDEVICESENSOR_TEMPERATURE = _ok.okDEVICESENSOR_TEMPERATURE
okDEVICESENSOR_FAN_RPM = _ok.okDEVICESENSOR_FAN_RPM
OK_MAX_DEVICE_SENSOR_NAME_LENGTH = _ok.OK_MAX_DEVICE_SENSOR_NAME_LENGTH
OK_MAX_DEVICE_SENSOR_DESCRIPTION_LENGTH = _ok.OK_MAX_DEVICE_SENSOR_DESCRIPTION_LENGTH
class okTDeviceSensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTDeviceSensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTDeviceSensor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["id"] = _ok.okTDeviceSensor_id_set
    __swig_getmethods__["id"] = _ok.okTDeviceSensor_id_get
    if _newclass:id = _swig_property(_ok.okTDeviceSensor_id_get, _ok.okTDeviceSensor_id_set)
    __swig_setmethods__["type"] = _ok.okTDeviceSensor_type_set
    __swig_getmethods__["type"] = _ok.okTDeviceSensor_type_get
    if _newclass:type = _swig_property(_ok.okTDeviceSensor_type_get, _ok.okTDeviceSensor_type_set)
    __swig_setmethods__["name"] = _ok.okTDeviceSensor_name_set
    __swig_getmethods__["name"] = _ok.okTDeviceSensor_name_get
    if _newclass:name = _swig_property(_ok.okTDeviceSensor_name_get, _ok.okTDeviceSensor_name_set)
    __swig_setmethods__["description"] = _ok.okTDeviceSensor_description_set
    __swig_getmethods__["description"] = _ok.okTDeviceSensor_description_get
    if _newclass:description = _swig_property(_ok.okTDeviceSensor_description_get, _ok.okTDeviceSensor_description_set)
    __swig_setmethods__["min"] = _ok.okTDeviceSensor_min_set
    __swig_getmethods__["min"] = _ok.okTDeviceSensor_min_get
    if _newclass:min = _swig_property(_ok.okTDeviceSensor_min_get, _ok.okTDeviceSensor_min_set)
    __swig_setmethods__["max"] = _ok.okTDeviceSensor_max_set
    __swig_getmethods__["max"] = _ok.okTDeviceSensor_max_get
    if _newclass:max = _swig_property(_ok.okTDeviceSensor_max_get, _ok.okTDeviceSensor_max_set)
    __swig_setmethods__["step"] = _ok.okTDeviceSensor_step_set
    __swig_getmethods__["step"] = _ok.okTDeviceSensor_step_get
    if _newclass:step = _swig_property(_ok.okTDeviceSensor_step_get, _ok.okTDeviceSensor_step_set)
    __swig_setmethods__["value"] = _ok.okTDeviceSensor_value_set
    __swig_getmethods__["value"] = _ok.okTDeviceSensor_value_get
    if _newclass:value = _swig_property(_ok.okTDeviceSensor_value_get, _ok.okTDeviceSensor_value_set)
    def __init__(self): 
        this = _ok.new_okTDeviceSensor()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTDeviceSensor
    __del__ = lambda self : None;
okTDeviceSensor_swigregister = _ok.okTDeviceSensor_swigregister
okTDeviceSensor_swigregister(okTDeviceSensor)

OK_PRODUCT_UNKNOWN = _ok.OK_PRODUCT_UNKNOWN
OK_PRODUCT_XEM3001V1 = _ok.OK_PRODUCT_XEM3001V1
OK_PRODUCT_XEM3001V2 = _ok.OK_PRODUCT_XEM3001V2
OK_PRODUCT_XEM3010 = _ok.OK_PRODUCT_XEM3010
OK_PRODUCT_XEM3005 = _ok.OK_PRODUCT_XEM3005
OK_PRODUCT_XEM3001CL = _ok.OK_PRODUCT_XEM3001CL
OK_PRODUCT_XEM3020 = _ok.OK_PRODUCT_XEM3020
OK_PRODUCT_XEM3050 = _ok.OK_PRODUCT_XEM3050
OK_PRODUCT_XEM9002 = _ok.OK_PRODUCT_XEM9002
OK_PRODUCT_XEM3001RB = _ok.OK_PRODUCT_XEM3001RB
OK_PRODUCT_XEM5010 = _ok.OK_PRODUCT_XEM5010
OK_PRODUCT_XEM6110LX45 = _ok.OK_PRODUCT_XEM6110LX45
OK_PRODUCT_XEM6001 = _ok.OK_PRODUCT_XEM6001
OK_PRODUCT_XEM6010LX45 = _ok.OK_PRODUCT_XEM6010LX45
OK_PRODUCT_XEM6010LX150 = _ok.OK_PRODUCT_XEM6010LX150
OK_PRODUCT_XEM6110LX150 = _ok.OK_PRODUCT_XEM6110LX150
OK_PRODUCT_XEM6006LX9 = _ok.OK_PRODUCT_XEM6006LX9
OK_PRODUCT_XEM6006LX16 = _ok.OK_PRODUCT_XEM6006LX16
OK_PRODUCT_XEM6006LX25 = _ok.OK_PRODUCT_XEM6006LX25
OK_PRODUCT_XEM5010LX110 = _ok.OK_PRODUCT_XEM5010LX110
OK_PRODUCT_ZEM4310 = _ok.OK_PRODUCT_ZEM4310
OK_PRODUCT_XEM6310LX45 = _ok.OK_PRODUCT_XEM6310LX45
OK_PRODUCT_XEM6310LX150 = _ok.OK_PRODUCT_XEM6310LX150
OK_PRODUCT_XEM6110V2LX45 = _ok.OK_PRODUCT_XEM6110V2LX45
OK_PRODUCT_XEM6110V2LX150 = _ok.OK_PRODUCT_XEM6110V2LX150
OK_PRODUCT_XEM6002LX9 = _ok.OK_PRODUCT_XEM6002LX9
OK_PRODUCT_XEM6310MTLX45T = _ok.OK_PRODUCT_XEM6310MTLX45T
OK_PRODUCT_XEM6320LX130T = _ok.OK_PRODUCT_XEM6320LX130T
OK_PRODUCT_XEM7350K70T = _ok.OK_PRODUCT_XEM7350K70T
OK_PRODUCT_XEM7350K160T = _ok.OK_PRODUCT_XEM7350K160T
OK_PRODUCT_XEM7350K410T = _ok.OK_PRODUCT_XEM7350K410T
OK_PRODUCT_XEM6310MTLX150T = _ok.OK_PRODUCT_XEM6310MTLX150T
OK_PRODUCT_ZEM5305A2 = _ok.OK_PRODUCT_ZEM5305A2
OK_PRODUCT_ZEM5305A7 = _ok.OK_PRODUCT_ZEM5305A7
OK_PRODUCT_XEM7001A15 = _ok.OK_PRODUCT_XEM7001A15
OK_PRODUCT_XEM7001A35 = _ok.OK_PRODUCT_XEM7001A35
OK_PRODUCT_XEM7360K160T = _ok.OK_PRODUCT_XEM7360K160T
OK_PRODUCT_XEM7360K410T = _ok.OK_PRODUCT_XEM7360K410T
OK_PRODUCT_ZEM5310A4 = _ok.OK_PRODUCT_ZEM5310A4
OK_PRODUCT_ZEM5310A7 = _ok.OK_PRODUCT_ZEM5310A7
OK_PRODUCT_ZEM5370A5 = _ok.OK_PRODUCT_ZEM5370A5
OK_PRODUCT_XEM7010A50 = _ok.OK_PRODUCT_XEM7010A50
OK_PRODUCT_XEM7010A200 = _ok.OK_PRODUCT_XEM7010A200
OK_PRODUCT_XEM7310A75 = _ok.OK_PRODUCT_XEM7310A75
OK_PRODUCT_XEM7310A200 = _ok.OK_PRODUCT_XEM7310A200
OK_PRODUCT_XEM7320A75T = _ok.OK_PRODUCT_XEM7320A75T
OK_PRODUCT_XEM7320A200T = _ok.OK_PRODUCT_XEM7320A200T
OK_PRODUCT_XEM7305 = _ok.OK_PRODUCT_XEM7305
OK_PRODUCT_OEM_START = _ok.OK_PRODUCT_OEM_START
okPRODUCT_UNKNOWN = _ok.okPRODUCT_UNKNOWN
okPRODUCT_XEM3001V1 = _ok.okPRODUCT_XEM3001V1
okPRODUCT_XEM3001V2 = _ok.okPRODUCT_XEM3001V2
okPRODUCT_XEM3010 = _ok.okPRODUCT_XEM3010
okPRODUCT_XEM3005 = _ok.okPRODUCT_XEM3005
okPRODUCT_XEM3001CL = _ok.okPRODUCT_XEM3001CL
okPRODUCT_XEM3020 = _ok.okPRODUCT_XEM3020
okPRODUCT_XEM3050 = _ok.okPRODUCT_XEM3050
okPRODUCT_XEM9002 = _ok.okPRODUCT_XEM9002
okPRODUCT_XEM3001RB = _ok.okPRODUCT_XEM3001RB
okPRODUCT_XEM5010 = _ok.okPRODUCT_XEM5010
okPRODUCT_XEM6110LX45 = _ok.okPRODUCT_XEM6110LX45
okPRODUCT_XEM6001 = _ok.okPRODUCT_XEM6001
okPRODUCT_XEM6010LX45 = _ok.okPRODUCT_XEM6010LX45
okPRODUCT_XEM6010LX150 = _ok.okPRODUCT_XEM6010LX150
okPRODUCT_XEM6110LX150 = _ok.okPRODUCT_XEM6110LX150
okPRODUCT_XEM6006LX9 = _ok.okPRODUCT_XEM6006LX9
okPRODUCT_XEM6006LX16 = _ok.okPRODUCT_XEM6006LX16
okPRODUCT_XEM6006LX25 = _ok.okPRODUCT_XEM6006LX25
okPRODUCT_XEM5010LX110 = _ok.okPRODUCT_XEM5010LX110
okPRODUCT_ZEM4310 = _ok.okPRODUCT_ZEM4310
okPRODUCT_XEM6310LX45 = _ok.okPRODUCT_XEM6310LX45
okPRODUCT_XEM6310LX150 = _ok.okPRODUCT_XEM6310LX150
okPRODUCT_XEM6110V2LX45 = _ok.okPRODUCT_XEM6110V2LX45
okPRODUCT_XEM6110V2LX150 = _ok.okPRODUCT_XEM6110V2LX150
okPRODUCT_XEM6002LX9 = _ok.okPRODUCT_XEM6002LX9
okPRODUCT_XEM6310MTLX45T = _ok.okPRODUCT_XEM6310MTLX45T
okPRODUCT_XEM6320LX130T = _ok.okPRODUCT_XEM6320LX130T
okPRODUCT_XEM7350K70T = _ok.okPRODUCT_XEM7350K70T
okPRODUCT_XEM7350K160T = _ok.okPRODUCT_XEM7350K160T
okPRODUCT_XEM7350K410T = _ok.okPRODUCT_XEM7350K410T
okPRODUCT_XEM6310MTLX150T = _ok.okPRODUCT_XEM6310MTLX150T
okPRODUCT_ZEM5305A2 = _ok.okPRODUCT_ZEM5305A2
okPRODUCT_ZEM5305A7 = _ok.okPRODUCT_ZEM5305A7
okPRODUCT_XEM7001A15 = _ok.okPRODUCT_XEM7001A15
okPRODUCT_XEM7001A35 = _ok.okPRODUCT_XEM7001A35
okPRODUCT_XEM7360K160T = _ok.okPRODUCT_XEM7360K160T
okPRODUCT_XEM7360K410T = _ok.okPRODUCT_XEM7360K410T
okPRODUCT_ZEM5310A4 = _ok.okPRODUCT_ZEM5310A4
okPRODUCT_ZEM5310A7 = _ok.okPRODUCT_ZEM5310A7
okPRODUCT_ZEM5370A5 = _ok.okPRODUCT_ZEM5370A5
okPRODUCT_XEM7010A50 = _ok.okPRODUCT_XEM7010A50
okPRODUCT_XEM7010A200 = _ok.okPRODUCT_XEM7010A200
okPRODUCT_XEM7310A75 = _ok.okPRODUCT_XEM7310A75
okPRODUCT_XEM7310A200 = _ok.okPRODUCT_XEM7310A200
okPRODUCT_XEM7320A75T = _ok.okPRODUCT_XEM7320A75T
okPRODUCT_XEM7320A200T = _ok.okPRODUCT_XEM7320A200T
okPRODUCT_XEM7305 = _ok.okPRODUCT_XEM7305
okPRODUCT_OEM_START = _ok.okPRODUCT_OEM_START
class okTRegisterEntry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTRegisterEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTRegisterEntry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["address"] = _ok.okTRegisterEntry_address_set
    __swig_getmethods__["address"] = _ok.okTRegisterEntry_address_get
    if _newclass:address = _swig_property(_ok.okTRegisterEntry_address_get, _ok.okTRegisterEntry_address_set)
    __swig_setmethods__["data"] = _ok.okTRegisterEntry_data_set
    __swig_getmethods__["data"] = _ok.okTRegisterEntry_data_get
    if _newclass:data = _swig_property(_ok.okTRegisterEntry_data_get, _ok.okTRegisterEntry_data_set)
    def __init__(self): 
        this = _ok.new_okTRegisterEntry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTRegisterEntry
    __del__ = lambda self : None;
okTRegisterEntry_swigregister = _ok.okTRegisterEntry_swigregister
okTRegisterEntry_swigregister(okTRegisterEntry)

class okTTriggerEntry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTTriggerEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTTriggerEntry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["address"] = _ok.okTTriggerEntry_address_set
    __swig_getmethods__["address"] = _ok.okTTriggerEntry_address_get
    if _newclass:address = _swig_property(_ok.okTTriggerEntry_address_get, _ok.okTTriggerEntry_address_set)
    __swig_setmethods__["mask"] = _ok.okTTriggerEntry_mask_set
    __swig_getmethods__["mask"] = _ok.okTTriggerEntry_mask_get
    if _newclass:mask = _swig_property(_ok.okTTriggerEntry_mask_get, _ok.okTTriggerEntry_mask_set)
    def __init__(self): 
        this = _ok.new_okTTriggerEntry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTTriggerEntry
    __del__ = lambda self : None;
okTTriggerEntry_swigregister = _ok.okTTriggerEntry_swigregister
okTTriggerEntry_swigregister(okTTriggerEntry)

OK_FPGACONFIGURATIONMETHOD_NVRAM = _ok.OK_FPGACONFIGURATIONMETHOD_NVRAM
OK_FPGACONFIGURATIONMETHOD_JTAG = _ok.OK_FPGACONFIGURATIONMETHOD_JTAG
okFPGACONFIGURATIONMETHOD_NVRAM = _ok.okFPGACONFIGURATIONMETHOD_NVRAM
okFPGACONFIGURATIONMETHOD_JTAG = _ok.okFPGACONFIGURATIONMETHOD_JTAG
okFPGARESETPROFILE_MAGIC = _ok.okFPGARESETPROFILE_MAGIC
class okTFPGAResetProfile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTFPGAResetProfile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTFPGAResetProfile, name)
    __repr__ = _swig_repr
    __swig_setmethods__["magic"] = _ok.okTFPGAResetProfile_magic_set
    __swig_getmethods__["magic"] = _ok.okTFPGAResetProfile_magic_get
    if _newclass:magic = _swig_property(_ok.okTFPGAResetProfile_magic_get, _ok.okTFPGAResetProfile_magic_set)
    __swig_setmethods__["configFileLocation"] = _ok.okTFPGAResetProfile_configFileLocation_set
    __swig_getmethods__["configFileLocation"] = _ok.okTFPGAResetProfile_configFileLocation_get
    if _newclass:configFileLocation = _swig_property(_ok.okTFPGAResetProfile_configFileLocation_get, _ok.okTFPGAResetProfile_configFileLocation_set)
    __swig_setmethods__["configFileLength"] = _ok.okTFPGAResetProfile_configFileLength_set
    __swig_getmethods__["configFileLength"] = _ok.okTFPGAResetProfile_configFileLength_get
    if _newclass:configFileLength = _swig_property(_ok.okTFPGAResetProfile_configFileLength_get, _ok.okTFPGAResetProfile_configFileLength_set)
    __swig_setmethods__["doneWaitUS"] = _ok.okTFPGAResetProfile_doneWaitUS_set
    __swig_getmethods__["doneWaitUS"] = _ok.okTFPGAResetProfile_doneWaitUS_get
    if _newclass:doneWaitUS = _swig_property(_ok.okTFPGAResetProfile_doneWaitUS_get, _ok.okTFPGAResetProfile_doneWaitUS_set)
    __swig_setmethods__["resetWaitUS"] = _ok.okTFPGAResetProfile_resetWaitUS_set
    __swig_getmethods__["resetWaitUS"] = _ok.okTFPGAResetProfile_resetWaitUS_get
    if _newclass:resetWaitUS = _swig_property(_ok.okTFPGAResetProfile_resetWaitUS_get, _ok.okTFPGAResetProfile_resetWaitUS_set)
    __swig_setmethods__["registerWaitUS"] = _ok.okTFPGAResetProfile_registerWaitUS_set
    __swig_getmethods__["registerWaitUS"] = _ok.okTFPGAResetProfile_registerWaitUS_get
    if _newclass:registerWaitUS = _swig_property(_ok.okTFPGAResetProfile_registerWaitUS_get, _ok.okTFPGAResetProfile_registerWaitUS_set)
    __swig_setmethods__["padBytes1"] = _ok.okTFPGAResetProfile_padBytes1_set
    __swig_getmethods__["padBytes1"] = _ok.okTFPGAResetProfile_padBytes1_get
    if _newclass:padBytes1 = _swig_property(_ok.okTFPGAResetProfile_padBytes1_get, _ok.okTFPGAResetProfile_padBytes1_set)
    __swig_setmethods__["wireInValues"] = _ok.okTFPGAResetProfile_wireInValues_set
    __swig_getmethods__["wireInValues"] = _ok.okTFPGAResetProfile_wireInValues_get
    if _newclass:wireInValues = _swig_property(_ok.okTFPGAResetProfile_wireInValues_get, _ok.okTFPGAResetProfile_wireInValues_set)
    __swig_setmethods__["registerEntryCount"] = _ok.okTFPGAResetProfile_registerEntryCount_set
    __swig_getmethods__["registerEntryCount"] = _ok.okTFPGAResetProfile_registerEntryCount_get
    if _newclass:registerEntryCount = _swig_property(_ok.okTFPGAResetProfile_registerEntryCount_get, _ok.okTFPGAResetProfile_registerEntryCount_set)
    __swig_setmethods__["registerEntries"] = _ok.okTFPGAResetProfile_registerEntries_set
    __swig_getmethods__["registerEntries"] = _ok.okTFPGAResetProfile_registerEntries_get
    if _newclass:registerEntries = _swig_property(_ok.okTFPGAResetProfile_registerEntries_get, _ok.okTFPGAResetProfile_registerEntries_set)
    __swig_setmethods__["triggerEntryCount"] = _ok.okTFPGAResetProfile_triggerEntryCount_set
    __swig_getmethods__["triggerEntryCount"] = _ok.okTFPGAResetProfile_triggerEntryCount_get
    if _newclass:triggerEntryCount = _swig_property(_ok.okTFPGAResetProfile_triggerEntryCount_get, _ok.okTFPGAResetProfile_triggerEntryCount_set)
    __swig_setmethods__["triggerEntries"] = _ok.okTFPGAResetProfile_triggerEntries_set
    __swig_getmethods__["triggerEntries"] = _ok.okTFPGAResetProfile_triggerEntries_get
    if _newclass:triggerEntries = _swig_property(_ok.okTFPGAResetProfile_triggerEntries_get, _ok.okTFPGAResetProfile_triggerEntries_set)
    __swig_setmethods__["padBytes2"] = _ok.okTFPGAResetProfile_padBytes2_set
    __swig_getmethods__["padBytes2"] = _ok.okTFPGAResetProfile_padBytes2_get
    if _newclass:padBytes2 = _swig_property(_ok.okTFPGAResetProfile_padBytes2_get, _ok.okTFPGAResetProfile_padBytes2_set)
    def __init__(self): 
        this = _ok.new_okTFPGAResetProfile()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTFPGAResetProfile
    __del__ = lambda self : None;
okTFPGAResetProfile_swigregister = _ok.okTFPGAResetProfile_swigregister
okTFPGAResetProfile_swigregister(okTFPGAResetProfile)

class okTFlashLayout(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTFlashLayout, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTFlashLayout, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sectorCount"] = _ok.okTFlashLayout_sectorCount_set
    __swig_getmethods__["sectorCount"] = _ok.okTFlashLayout_sectorCount_get
    if _newclass:sectorCount = _swig_property(_ok.okTFlashLayout_sectorCount_get, _ok.okTFlashLayout_sectorCount_set)
    __swig_setmethods__["sectorSize"] = _ok.okTFlashLayout_sectorSize_set
    __swig_getmethods__["sectorSize"] = _ok.okTFlashLayout_sectorSize_get
    if _newclass:sectorSize = _swig_property(_ok.okTFlashLayout_sectorSize_get, _ok.okTFlashLayout_sectorSize_set)
    __swig_setmethods__["pageSize"] = _ok.okTFlashLayout_pageSize_set
    __swig_getmethods__["pageSize"] = _ok.okTFlashLayout_pageSize_get
    if _newclass:pageSize = _swig_property(_ok.okTFlashLayout_pageSize_get, _ok.okTFlashLayout_pageSize_set)
    __swig_setmethods__["minUserSector"] = _ok.okTFlashLayout_minUserSector_set
    __swig_getmethods__["minUserSector"] = _ok.okTFlashLayout_minUserSector_get
    if _newclass:minUserSector = _swig_property(_ok.okTFlashLayout_minUserSector_get, _ok.okTFlashLayout_minUserSector_set)
    __swig_setmethods__["maxUserSector"] = _ok.okTFlashLayout_maxUserSector_set
    __swig_getmethods__["maxUserSector"] = _ok.okTFlashLayout_maxUserSector_get
    if _newclass:maxUserSector = _swig_property(_ok.okTFlashLayout_maxUserSector_get, _ok.okTFlashLayout_maxUserSector_set)
    def __init__(self): 
        this = _ok.new_okTFlashLayout()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTFlashLayout
    __del__ = lambda self : None;
okTFlashLayout_swigregister = _ok.okTFlashLayout_swigregister
okTFlashLayout_swigregister(okTFlashLayout)

class okTDeviceMatchInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTDeviceMatchInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTDeviceMatchInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["productName"] = _ok.okTDeviceMatchInfo_productName_set
    __swig_getmethods__["productName"] = _ok.okTDeviceMatchInfo_productName_get
    if _newclass:productName = _swig_property(_ok.okTDeviceMatchInfo_productName_get, _ok.okTDeviceMatchInfo_productName_set)
    __swig_setmethods__["productBaseID"] = _ok.okTDeviceMatchInfo_productBaseID_set
    __swig_getmethods__["productBaseID"] = _ok.okTDeviceMatchInfo_productBaseID_get
    if _newclass:productBaseID = _swig_property(_ok.okTDeviceMatchInfo_productBaseID_get, _ok.okTDeviceMatchInfo_productBaseID_set)
    __swig_setmethods__["productID"] = _ok.okTDeviceMatchInfo_productID_set
    __swig_getmethods__["productID"] = _ok.okTDeviceMatchInfo_productID_get
    if _newclass:productID = _swig_property(_ok.okTDeviceMatchInfo_productID_get, _ok.okTDeviceMatchInfo_productID_set)
    __swig_setmethods__["usbVID"] = _ok.okTDeviceMatchInfo_usbVID_set
    __swig_getmethods__["usbVID"] = _ok.okTDeviceMatchInfo_usbVID_get
    if _newclass:usbVID = _swig_property(_ok.okTDeviceMatchInfo_usbVID_get, _ok.okTDeviceMatchInfo_usbVID_set)
    __swig_setmethods__["usbPID"] = _ok.okTDeviceMatchInfo_usbPID_set
    __swig_getmethods__["usbPID"] = _ok.okTDeviceMatchInfo_usbPID_get
    if _newclass:usbPID = _swig_property(_ok.okTDeviceMatchInfo_usbPID_get, _ok.okTDeviceMatchInfo_usbPID_set)
    __swig_setmethods__["pciDID"] = _ok.okTDeviceMatchInfo_pciDID_set
    __swig_getmethods__["pciDID"] = _ok.okTDeviceMatchInfo_pciDID_get
    if _newclass:pciDID = _swig_property(_ok.okTDeviceMatchInfo_pciDID_get, _ok.okTDeviceMatchInfo_pciDID_set)
    def __init__(self): 
        this = _ok.new_okTDeviceMatchInfo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTDeviceMatchInfo
    __del__ = lambda self : None;
okTDeviceMatchInfo_swigregister = _ok.okTDeviceMatchInfo_swigregister
okTDeviceMatchInfo_swigregister(okTDeviceMatchInfo)

class okTDeviceInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTDeviceInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTDeviceInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["deviceID"] = _ok.okTDeviceInfo_deviceID_set
    __swig_getmethods__["deviceID"] = _ok.okTDeviceInfo_deviceID_get
    if _newclass:deviceID = _swig_property(_ok.okTDeviceInfo_deviceID_get, _ok.okTDeviceInfo_deviceID_set)
    __swig_setmethods__["serialNumber"] = _ok.okTDeviceInfo_serialNumber_set
    __swig_getmethods__["serialNumber"] = _ok.okTDeviceInfo_serialNumber_get
    if _newclass:serialNumber = _swig_property(_ok.okTDeviceInfo_serialNumber_get, _ok.okTDeviceInfo_serialNumber_set)
    __swig_setmethods__["productName"] = _ok.okTDeviceInfo_productName_set
    __swig_getmethods__["productName"] = _ok.okTDeviceInfo_productName_get
    if _newclass:productName = _swig_property(_ok.okTDeviceInfo_productName_get, _ok.okTDeviceInfo_productName_set)
    __swig_setmethods__["productID"] = _ok.okTDeviceInfo_productID_set
    __swig_getmethods__["productID"] = _ok.okTDeviceInfo_productID_get
    if _newclass:productID = _swig_property(_ok.okTDeviceInfo_productID_get, _ok.okTDeviceInfo_productID_set)
    __swig_setmethods__["deviceInterface"] = _ok.okTDeviceInfo_deviceInterface_set
    __swig_getmethods__["deviceInterface"] = _ok.okTDeviceInfo_deviceInterface_get
    if _newclass:deviceInterface = _swig_property(_ok.okTDeviceInfo_deviceInterface_get, _ok.okTDeviceInfo_deviceInterface_set)
    __swig_setmethods__["usbSpeed"] = _ok.okTDeviceInfo_usbSpeed_set
    __swig_getmethods__["usbSpeed"] = _ok.okTDeviceInfo_usbSpeed_get
    if _newclass:usbSpeed = _swig_property(_ok.okTDeviceInfo_usbSpeed_get, _ok.okTDeviceInfo_usbSpeed_set)
    __swig_setmethods__["deviceMajorVersion"] = _ok.okTDeviceInfo_deviceMajorVersion_set
    __swig_getmethods__["deviceMajorVersion"] = _ok.okTDeviceInfo_deviceMajorVersion_get
    if _newclass:deviceMajorVersion = _swig_property(_ok.okTDeviceInfo_deviceMajorVersion_get, _ok.okTDeviceInfo_deviceMajorVersion_set)
    __swig_setmethods__["deviceMinorVersion"] = _ok.okTDeviceInfo_deviceMinorVersion_set
    __swig_getmethods__["deviceMinorVersion"] = _ok.okTDeviceInfo_deviceMinorVersion_get
    if _newclass:deviceMinorVersion = _swig_property(_ok.okTDeviceInfo_deviceMinorVersion_get, _ok.okTDeviceInfo_deviceMinorVersion_set)
    __swig_setmethods__["hostInterfaceMajorVersion"] = _ok.okTDeviceInfo_hostInterfaceMajorVersion_set
    __swig_getmethods__["hostInterfaceMajorVersion"] = _ok.okTDeviceInfo_hostInterfaceMajorVersion_get
    if _newclass:hostInterfaceMajorVersion = _swig_property(_ok.okTDeviceInfo_hostInterfaceMajorVersion_get, _ok.okTDeviceInfo_hostInterfaceMajorVersion_set)
    __swig_setmethods__["hostInterfaceMinorVersion"] = _ok.okTDeviceInfo_hostInterfaceMinorVersion_set
    __swig_getmethods__["hostInterfaceMinorVersion"] = _ok.okTDeviceInfo_hostInterfaceMinorVersion_get
    if _newclass:hostInterfaceMinorVersion = _swig_property(_ok.okTDeviceInfo_hostInterfaceMinorVersion_get, _ok.okTDeviceInfo_hostInterfaceMinorVersion_set)
    __swig_setmethods__["isPLL22150Supported"] = _ok.okTDeviceInfo_isPLL22150Supported_set
    __swig_getmethods__["isPLL22150Supported"] = _ok.okTDeviceInfo_isPLL22150Supported_get
    if _newclass:isPLL22150Supported = _swig_property(_ok.okTDeviceInfo_isPLL22150Supported_get, _ok.okTDeviceInfo_isPLL22150Supported_set)
    __swig_setmethods__["isPLL22393Supported"] = _ok.okTDeviceInfo_isPLL22393Supported_set
    __swig_getmethods__["isPLL22393Supported"] = _ok.okTDeviceInfo_isPLL22393Supported_get
    if _newclass:isPLL22393Supported = _swig_property(_ok.okTDeviceInfo_isPLL22393Supported_get, _ok.okTDeviceInfo_isPLL22393Supported_set)
    __swig_setmethods__["isFrontPanelEnabled"] = _ok.okTDeviceInfo_isFrontPanelEnabled_set
    __swig_getmethods__["isFrontPanelEnabled"] = _ok.okTDeviceInfo_isFrontPanelEnabled_get
    if _newclass:isFrontPanelEnabled = _swig_property(_ok.okTDeviceInfo_isFrontPanelEnabled_get, _ok.okTDeviceInfo_isFrontPanelEnabled_set)
    __swig_setmethods__["wireWidth"] = _ok.okTDeviceInfo_wireWidth_set
    __swig_getmethods__["wireWidth"] = _ok.okTDeviceInfo_wireWidth_get
    if _newclass:wireWidth = _swig_property(_ok.okTDeviceInfo_wireWidth_get, _ok.okTDeviceInfo_wireWidth_set)
    __swig_setmethods__["triggerWidth"] = _ok.okTDeviceInfo_triggerWidth_set
    __swig_getmethods__["triggerWidth"] = _ok.okTDeviceInfo_triggerWidth_get
    if _newclass:triggerWidth = _swig_property(_ok.okTDeviceInfo_triggerWidth_get, _ok.okTDeviceInfo_triggerWidth_set)
    __swig_setmethods__["pipeWidth"] = _ok.okTDeviceInfo_pipeWidth_set
    __swig_getmethods__["pipeWidth"] = _ok.okTDeviceInfo_pipeWidth_get
    if _newclass:pipeWidth = _swig_property(_ok.okTDeviceInfo_pipeWidth_get, _ok.okTDeviceInfo_pipeWidth_set)
    __swig_setmethods__["registerAddressWidth"] = _ok.okTDeviceInfo_registerAddressWidth_set
    __swig_getmethods__["registerAddressWidth"] = _ok.okTDeviceInfo_registerAddressWidth_get
    if _newclass:registerAddressWidth = _swig_property(_ok.okTDeviceInfo_registerAddressWidth_get, _ok.okTDeviceInfo_registerAddressWidth_set)
    __swig_setmethods__["registerDataWidth"] = _ok.okTDeviceInfo_registerDataWidth_set
    __swig_getmethods__["registerDataWidth"] = _ok.okTDeviceInfo_registerDataWidth_get
    if _newclass:registerDataWidth = _swig_property(_ok.okTDeviceInfo_registerDataWidth_get, _ok.okTDeviceInfo_registerDataWidth_set)
    __swig_setmethods__["flashSystem"] = _ok.okTDeviceInfo_flashSystem_set
    __swig_getmethods__["flashSystem"] = _ok.okTDeviceInfo_flashSystem_get
    if _newclass:flashSystem = _swig_property(_ok.okTDeviceInfo_flashSystem_get, _ok.okTDeviceInfo_flashSystem_set)
    __swig_setmethods__["flashFPGA"] = _ok.okTDeviceInfo_flashFPGA_set
    __swig_getmethods__["flashFPGA"] = _ok.okTDeviceInfo_flashFPGA_get
    if _newclass:flashFPGA = _swig_property(_ok.okTDeviceInfo_flashFPGA_get, _ok.okTDeviceInfo_flashFPGA_set)
    __swig_setmethods__["hasFMCEEPROM"] = _ok.okTDeviceInfo_hasFMCEEPROM_set
    __swig_getmethods__["hasFMCEEPROM"] = _ok.okTDeviceInfo_hasFMCEEPROM_get
    if _newclass:hasFMCEEPROM = _swig_property(_ok.okTDeviceInfo_hasFMCEEPROM_get, _ok.okTDeviceInfo_hasFMCEEPROM_set)
    __swig_setmethods__["hasResetProfiles"] = _ok.okTDeviceInfo_hasResetProfiles_set
    __swig_getmethods__["hasResetProfiles"] = _ok.okTDeviceInfo_hasResetProfiles_get
    if _newclass:hasResetProfiles = _swig_property(_ok.okTDeviceInfo_hasResetProfiles_get, _ok.okTDeviceInfo_hasResetProfiles_set)
    def __init__(self): 
        this = _ok.new_okTDeviceInfo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okTDeviceInfo
    __del__ = lambda self : None;
okTDeviceInfo_swigregister = _ok.okTDeviceInfo_swigregister
okTDeviceInfo_swigregister(okTDeviceInfo)

class okBuffer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okBuffer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okBuffer, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ok.new_okBuffer(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okBuffer
    __del__ = lambda self : None;
    def IsEmpty(self): return _ok.okBuffer_IsEmpty(self)
    def GetSize(self): return _ok.okBuffer_GetSize(self)
    def __getitem__(self, *args): return _ok.okBuffer___getitem__(self, *args)
    def __setitem__(self, *args): return _ok.okBuffer___setitem__(self, *args)
okBuffer_swigregister = _ok.okBuffer_swigregister
okBuffer_swigregister(okBuffer)

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ok.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _ok.SwigPyIterator_value(self)
    def incr(self, n=1): return _ok.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _ok.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _ok.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _ok.SwigPyIterator_equal(self, *args)
    def copy(self): return _ok.SwigPyIterator_copy(self)
    def next(self): return _ok.SwigPyIterator_next(self)
    def __next__(self): return _ok.SwigPyIterator___next__(self)
    def previous(self): return _ok.SwigPyIterator_previous(self)
    def advance(self, *args): return _ok.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _ok.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _ok.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _ok.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _ok.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _ok.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _ok.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _ok.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class okStrings(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okStrings, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okStrings, name)
    __repr__ = _swig_repr
    def iterator(self): return _ok.okStrings_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ok.okStrings___nonzero__(self)
    def __bool__(self): return _ok.okStrings___bool__(self)
    def __len__(self): return _ok.okStrings___len__(self)
    def pop(self): return _ok.okStrings_pop(self)
    def __getslice__(self, *args): return _ok.okStrings___getslice__(self, *args)
    def __setslice__(self, *args): return _ok.okStrings___setslice__(self, *args)
    def __delslice__(self, *args): return _ok.okStrings___delslice__(self, *args)
    def __delitem__(self, *args): return _ok.okStrings___delitem__(self, *args)
    def __getitem__(self, *args): return _ok.okStrings___getitem__(self, *args)
    def __setitem__(self, *args): return _ok.okStrings___setitem__(self, *args)
    def append(self, *args): return _ok.okStrings_append(self, *args)
    def empty(self): return _ok.okStrings_empty(self)
    def size(self): return _ok.okStrings_size(self)
    def clear(self): return _ok.okStrings_clear(self)
    def swap(self, *args): return _ok.okStrings_swap(self, *args)
    def get_allocator(self): return _ok.okStrings_get_allocator(self)
    def begin(self): return _ok.okStrings_begin(self)
    def end(self): return _ok.okStrings_end(self)
    def rbegin(self): return _ok.okStrings_rbegin(self)
    def rend(self): return _ok.okStrings_rend(self)
    def pop_back(self): return _ok.okStrings_pop_back(self)
    def erase(self, *args): return _ok.okStrings_erase(self, *args)
    def __init__(self, *args): 
        this = _ok.new_okStrings(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ok.okStrings_push_back(self, *args)
    def front(self): return _ok.okStrings_front(self)
    def back(self): return _ok.okStrings_back(self)
    def assign(self, *args): return _ok.okStrings_assign(self, *args)
    def resize(self, *args): return _ok.okStrings_resize(self, *args)
    def insert(self, *args): return _ok.okStrings_insert(self, *args)
    def reserve(self, *args): return _ok.okStrings_reserve(self, *args)
    def capacity(self): return _ok.okStrings_capacity(self)
    __swig_destroy__ = _ok.delete_okStrings
    __del__ = lambda self : None;
okStrings_swigregister = _ok.okStrings_swigregister
okStrings_swigregister(okStrings)

__version__ = "5.0.1"

class okTRegisterEntries(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okTRegisterEntries, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okTRegisterEntries, name)
    __repr__ = _swig_repr
    def iterator(self): return _ok.okTRegisterEntries_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ok.okTRegisterEntries___nonzero__(self)
    def __bool__(self): return _ok.okTRegisterEntries___bool__(self)
    def __len__(self): return _ok.okTRegisterEntries___len__(self)
    def pop(self): return _ok.okTRegisterEntries_pop(self)
    def __getslice__(self, *args): return _ok.okTRegisterEntries___getslice__(self, *args)
    def __setslice__(self, *args): return _ok.okTRegisterEntries___setslice__(self, *args)
    def __delslice__(self, *args): return _ok.okTRegisterEntries___delslice__(self, *args)
    def __delitem__(self, *args): return _ok.okTRegisterEntries___delitem__(self, *args)
    def __getitem__(self, *args): return _ok.okTRegisterEntries___getitem__(self, *args)
    def __setitem__(self, *args): return _ok.okTRegisterEntries___setitem__(self, *args)
    def append(self, *args): return _ok.okTRegisterEntries_append(self, *args)
    def empty(self): return _ok.okTRegisterEntries_empty(self)
    def size(self): return _ok.okTRegisterEntries_size(self)
    def clear(self): return _ok.okTRegisterEntries_clear(self)
    def swap(self, *args): return _ok.okTRegisterEntries_swap(self, *args)
    def get_allocator(self): return _ok.okTRegisterEntries_get_allocator(self)
    def begin(self): return _ok.okTRegisterEntries_begin(self)
    def end(self): return _ok.okTRegisterEntries_end(self)
    def rbegin(self): return _ok.okTRegisterEntries_rbegin(self)
    def rend(self): return _ok.okTRegisterEntries_rend(self)
    def pop_back(self): return _ok.okTRegisterEntries_pop_back(self)
    def erase(self, *args): return _ok.okTRegisterEntries_erase(self, *args)
    def __init__(self, *args): 
        this = _ok.new_okTRegisterEntries(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ok.okTRegisterEntries_push_back(self, *args)
    def front(self): return _ok.okTRegisterEntries_front(self)
    def back(self): return _ok.okTRegisterEntries_back(self)
    def assign(self, *args): return _ok.okTRegisterEntries_assign(self, *args)
    def resize(self, *args): return _ok.okTRegisterEntries_resize(self, *args)
    def insert(self, *args): return _ok.okTRegisterEntries_insert(self, *args)
    def reserve(self, *args): return _ok.okTRegisterEntries_reserve(self, *args)
    def capacity(self): return _ok.okTRegisterEntries_capacity(self)
    __swig_destroy__ = _ok.delete_okTRegisterEntries
    __del__ = lambda self : None;
okTRegisterEntries_swigregister = _ok.okTRegisterEntries_swigregister
okTRegisterEntries_swigregister(okTRegisterEntries)

class okDeviceSensors(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okDeviceSensors, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okDeviceSensors, name)
    __repr__ = _swig_repr
    def iterator(self): return _ok.okDeviceSensors_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ok.okDeviceSensors___nonzero__(self)
    def __bool__(self): return _ok.okDeviceSensors___bool__(self)
    def __len__(self): return _ok.okDeviceSensors___len__(self)
    def pop(self): return _ok.okDeviceSensors_pop(self)
    def __getslice__(self, *args): return _ok.okDeviceSensors___getslice__(self, *args)
    def __setslice__(self, *args): return _ok.okDeviceSensors___setslice__(self, *args)
    def __delslice__(self, *args): return _ok.okDeviceSensors___delslice__(self, *args)
    def __delitem__(self, *args): return _ok.okDeviceSensors___delitem__(self, *args)
    def __getitem__(self, *args): return _ok.okDeviceSensors___getitem__(self, *args)
    def __setitem__(self, *args): return _ok.okDeviceSensors___setitem__(self, *args)
    def append(self, *args): return _ok.okDeviceSensors_append(self, *args)
    def empty(self): return _ok.okDeviceSensors_empty(self)
    def size(self): return _ok.okDeviceSensors_size(self)
    def clear(self): return _ok.okDeviceSensors_clear(self)
    def swap(self, *args): return _ok.okDeviceSensors_swap(self, *args)
    def get_allocator(self): return _ok.okDeviceSensors_get_allocator(self)
    def begin(self): return _ok.okDeviceSensors_begin(self)
    def end(self): return _ok.okDeviceSensors_end(self)
    def rbegin(self): return _ok.okDeviceSensors_rbegin(self)
    def rend(self): return _ok.okDeviceSensors_rend(self)
    def pop_back(self): return _ok.okDeviceSensors_pop_back(self)
    def erase(self, *args): return _ok.okDeviceSensors_erase(self, *args)
    def __init__(self, *args): 
        this = _ok.new_okDeviceSensors(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ok.okDeviceSensors_push_back(self, *args)
    def front(self): return _ok.okDeviceSensors_front(self)
    def back(self): return _ok.okDeviceSensors_back(self)
    def assign(self, *args): return _ok.okDeviceSensors_assign(self, *args)
    def resize(self, *args): return _ok.okDeviceSensors_resize(self, *args)
    def insert(self, *args): return _ok.okDeviceSensors_insert(self, *args)
    def reserve(self, *args): return _ok.okDeviceSensors_reserve(self, *args)
    def capacity(self): return _ok.okDeviceSensors_capacity(self)
    __swig_destroy__ = _ok.delete_okDeviceSensors
    __del__ = lambda self : None;
okDeviceSensors_swigregister = _ok.okDeviceSensors_swigregister
okDeviceSensors_swigregister(okDeviceSensors)

class okCPLL22150(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCPLL22150, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCPLL22150, name)
    __repr__ = _swig_repr
    ClkSrc_Ref = _ok.okCPLL22150_ClkSrc_Ref
    ClkSrc_Div1ByN = _ok.okCPLL22150_ClkSrc_Div1ByN
    ClkSrc_Div1By2 = _ok.okCPLL22150_ClkSrc_Div1By2
    ClkSrc_Div1By3 = _ok.okCPLL22150_ClkSrc_Div1By3
    ClkSrc_Div2ByN = _ok.okCPLL22150_ClkSrc_Div2ByN
    ClkSrc_Div2By2 = _ok.okCPLL22150_ClkSrc_Div2By2
    ClkSrc_Div2By4 = _ok.okCPLL22150_ClkSrc_Div2By4
    DivSrc_Ref = _ok.okCPLL22150_DivSrc_Ref
    DivSrc_VCO = _ok.okCPLL22150_DivSrc_VCO
    def __init__(self): 
        this = _ok.new_okCPLL22150()
        try: self.this.append(this)
        except: self.this = this
    def SetCrystalLoad(self, *args): return _ok.okCPLL22150_SetCrystalLoad(self, *args)
    def SetReference(self, *args): return _ok.okCPLL22150_SetReference(self, *args)
    def GetReference(self): return _ok.okCPLL22150_GetReference(self)
    def SetVCOParameters(self, *args): return _ok.okCPLL22150_SetVCOParameters(self, *args)
    def GetVCOP(self): return _ok.okCPLL22150_GetVCOP(self)
    def GetVCOQ(self): return _ok.okCPLL22150_GetVCOQ(self)
    def GetVCOFrequency(self): return _ok.okCPLL22150_GetVCOFrequency(self)
    def SetDiv1(self, *args): return _ok.okCPLL22150_SetDiv1(self, *args)
    def SetDiv2(self, *args): return _ok.okCPLL22150_SetDiv2(self, *args)
    def GetDiv1Source(self): return _ok.okCPLL22150_GetDiv1Source(self)
    def GetDiv2Source(self): return _ok.okCPLL22150_GetDiv2Source(self)
    def GetDiv1Divider(self): return _ok.okCPLL22150_GetDiv1Divider(self)
    def GetDiv2Divider(self): return _ok.okCPLL22150_GetDiv2Divider(self)
    def SetOutputSource(self, *args): return _ok.okCPLL22150_SetOutputSource(self, *args)
    def SetOutputEnable(self, *args): return _ok.okCPLL22150_SetOutputEnable(self, *args)
    def GetOutputSource(self, *args): return _ok.okCPLL22150_GetOutputSource(self, *args)
    def GetOutputFrequency(self, *args): return _ok.okCPLL22150_GetOutputFrequency(self, *args)
    def IsOutputEnabled(self, *args): return _ok.okCPLL22150_IsOutputEnabled(self, *args)
    __swig_destroy__ = _ok.delete_okCPLL22150
    __del__ = lambda self : None;
okCPLL22150_swigregister = _ok.okCPLL22150_swigregister
okCPLL22150_swigregister(okCPLL22150)

class okCPLL22393(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCPLL22393, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCPLL22393, name)
    __repr__ = _swig_repr
    ClkSrc_Ref = _ok.okCPLL22393_ClkSrc_Ref
    ClkSrc_PLL0_0 = _ok.okCPLL22393_ClkSrc_PLL0_0
    ClkSrc_PLL0_180 = _ok.okCPLL22393_ClkSrc_PLL0_180
    ClkSrc_PLL1_0 = _ok.okCPLL22393_ClkSrc_PLL1_0
    ClkSrc_PLL1_180 = _ok.okCPLL22393_ClkSrc_PLL1_180
    ClkSrc_PLL2_0 = _ok.okCPLL22393_ClkSrc_PLL2_0
    ClkSrc_PLL2_180 = _ok.okCPLL22393_ClkSrc_PLL2_180
    def __init__(self): 
        this = _ok.new_okCPLL22393()
        try: self.this.append(this)
        except: self.this = this
    def SetCrystalLoad(self, *args): return _ok.okCPLL22393_SetCrystalLoad(self, *args)
    def SetReference(self, *args): return _ok.okCPLL22393_SetReference(self, *args)
    def SetPLLParameters(self, *args): return _ok.okCPLL22393_SetPLLParameters(self, *args)
    def SetPLLLF(self, *args): return _ok.okCPLL22393_SetPLLLF(self, *args)
    def SetOutputDivider(self, *args): return _ok.okCPLL22393_SetOutputDivider(self, *args)
    def SetOutputSource(self, *args): return _ok.okCPLL22393_SetOutputSource(self, *args)
    def SetOutputEnable(self, *args): return _ok.okCPLL22393_SetOutputEnable(self, *args)
    def GetReference(self): return _ok.okCPLL22393_GetReference(self)
    def GetPLLP(self, *args): return _ok.okCPLL22393_GetPLLP(self, *args)
    def GetPLLQ(self, *args): return _ok.okCPLL22393_GetPLLQ(self, *args)
    def GetPLLFrequency(self, *args): return _ok.okCPLL22393_GetPLLFrequency(self, *args)
    def GetOutputDivider(self, *args): return _ok.okCPLL22393_GetOutputDivider(self, *args)
    def GetOutputSource(self, *args): return _ok.okCPLL22393_GetOutputSource(self, *args)
    def GetOutputFrequency(self, *args): return _ok.okCPLL22393_GetOutputFrequency(self, *args)
    def IsOutputEnabled(self, *args): return _ok.okCPLL22393_IsOutputEnabled(self, *args)
    def IsPLLEnabled(self, *args): return _ok.okCPLL22393_IsPLLEnabled(self, *args)
    __swig_destroy__ = _ok.delete_okCPLL22393
    __del__ = lambda self : None;
okCPLL22393_swigregister = _ok.okCPLL22393_swigregister
okCPLL22393_swigregister(okCPLL22393)

class okCDeviceSettings(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCDeviceSettings, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCDeviceSettings, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ok.new_okCDeviceSettings()
        try: self.this.append(this)
        except: self.this = this
    def GetString(self, *args): return _ok.okCDeviceSettings_GetString(self, *args)
    def GetInt(self, *args): return _ok.okCDeviceSettings_GetInt(self, *args)
    def SetString(self, *args): return _ok.okCDeviceSettings_SetString(self, *args)
    def SetInt(self, *args): return _ok.okCDeviceSettings_SetInt(self, *args)
    def List(self): return _ok.okCDeviceSettings_List(self)
    def Delete(self, *args): return _ok.okCDeviceSettings_Delete(self, *args)
    def Save(self): return _ok.okCDeviceSettings_Save(self)
    __swig_destroy__ = _ok.delete_okCDeviceSettings
    __del__ = lambda self : None;
okCDeviceSettings_swigregister = _ok.okCDeviceSettings_swigregister
okCDeviceSettings_swigregister(okCDeviceSettings)

class okCFirmware(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCFirmware, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCFirmware, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def PerformTasks(self, *args): return _ok.okCFirmware_PerformTasks(self, *args)
    __swig_destroy__ = _ok.delete_okCFirmware
    __del__ = lambda self : None;
okCFirmware_swigregister = _ok.okCFirmware_swigregister
okCFirmware_swigregister(okCFirmware)

class okCFirmwarePackage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCFirmwarePackage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCFirmwarePackage, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ok.new_okCFirmwarePackage()
        try: self.this.append(this)
        except: self.this = this
    def Load(self, *args): return _ok.okCFirmwarePackage_Load(self, *args)
    def GetFirmwareCount(self): return _ok.okCFirmwarePackage_GetFirmwareCount(self)
    def GetFirmware(self, num=0): return _ok.okCFirmwarePackage_GetFirmware(self, num)
    __swig_destroy__ = _ok.delete_okCFirmwarePackage
    __del__ = lambda self : None;
okCFirmwarePackage_swigregister = _ok.okCFirmwarePackage_swigregister
okCFirmwarePackage_swigregister(okCFirmwarePackage)

class okCScriptValue(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCScriptValue, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCScriptValue, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ok.new_okCScriptValue(*args)
        try: self.this.append(this)
        except: self.this = this
    def IsNumber(self): return _ok.okCScriptValue_IsNumber(self)
    def GetNumber(self): return _ok.okCScriptValue_GetNumber(self)
    def IsBool(self): return _ok.okCScriptValue_IsBool(self)
    def GetBool(self): return _ok.okCScriptValue_GetBool(self)
    def IsString(self): return _ok.okCScriptValue_IsString(self)
    def GetString(self): return _ok.okCScriptValue_GetString(self)
    def IsBuffer(self): return _ok.okCScriptValue_IsBuffer(self)
    def GetBuffer(self): return _ok.okCScriptValue_GetBuffer(self)
    __swig_destroy__ = _ok.delete_okCScriptValue
    __del__ = lambda self : None;
okCScriptValue_swigregister = _ok.okCScriptValue_swigregister
okCScriptValue_swigregister(okCScriptValue)

class okCScriptValues(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCScriptValues, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCScriptValues, name)
    __repr__ = _swig_repr
    def iterator(self): return _ok.okCScriptValues_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ok.okCScriptValues___nonzero__(self)
    def __bool__(self): return _ok.okCScriptValues___bool__(self)
    def __len__(self): return _ok.okCScriptValues___len__(self)
    def pop(self): return _ok.okCScriptValues_pop(self)
    def __getslice__(self, *args): return _ok.okCScriptValues___getslice__(self, *args)
    def __setslice__(self, *args): return _ok.okCScriptValues___setslice__(self, *args)
    def __delslice__(self, *args): return _ok.okCScriptValues___delslice__(self, *args)
    def __delitem__(self, *args): return _ok.okCScriptValues___delitem__(self, *args)
    def __getitem__(self, *args): return _ok.okCScriptValues___getitem__(self, *args)
    def __setitem__(self, *args): return _ok.okCScriptValues___setitem__(self, *args)
    def append(self, *args): return _ok.okCScriptValues_append(self, *args)
    def empty(self): return _ok.okCScriptValues_empty(self)
    def size(self): return _ok.okCScriptValues_size(self)
    def clear(self): return _ok.okCScriptValues_clear(self)
    def swap(self, *args): return _ok.okCScriptValues_swap(self, *args)
    def get_allocator(self): return _ok.okCScriptValues_get_allocator(self)
    def begin(self): return _ok.okCScriptValues_begin(self)
    def end(self): return _ok.okCScriptValues_end(self)
    def rbegin(self): return _ok.okCScriptValues_rbegin(self)
    def rend(self): return _ok.okCScriptValues_rend(self)
    def pop_back(self): return _ok.okCScriptValues_pop_back(self)
    def erase(self, *args): return _ok.okCScriptValues_erase(self, *args)
    def __init__(self, *args): 
        this = _ok.new_okCScriptValues(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ok.okCScriptValues_push_back(self, *args)
    def front(self): return _ok.okCScriptValues_front(self)
    def back(self): return _ok.okCScriptValues_back(self)
    def assign(self, *args): return _ok.okCScriptValues_assign(self, *args)
    def resize(self, *args): return _ok.okCScriptValues_resize(self, *args)
    def insert(self, *args): return _ok.okCScriptValues_insert(self, *args)
    def reserve(self, *args): return _ok.okCScriptValues_reserve(self, *args)
    def capacity(self): return _ok.okCScriptValues_capacity(self)
    __swig_destroy__ = _ok.delete_okCScriptValues
    __del__ = lambda self : None;
okCScriptValues_swigregister = _ok.okCScriptValues_swigregister
okCScriptValues_swigregister(okCScriptValues)

class okCScriptEngine(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCScriptEngine, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCScriptEngine, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def LoadScript(self, *args): return _ok.okCScriptEngine_LoadScript(self, *args)
    def RunScriptFunction(self, *args): return _ok.okCScriptEngine_RunScriptFunction(self, *args)
    __swig_destroy__ = _ok.delete_okCScriptEngine
    __del__ = lambda self : None;
okCScriptEngine_swigregister = _ok.okCScriptEngine_swigregister
okCScriptEngine_swigregister(okCScriptEngine)

class okCFrontPanel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCFrontPanel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCFrontPanel, name)
    __repr__ = _swig_repr
    __swig_getmethods__["GetAPIVersionMajor"] = lambda x: _ok.okCFrontPanel_GetAPIVersionMajor
    if _newclass:GetAPIVersionMajor = staticmethod(_ok.okCFrontPanel_GetAPIVersionMajor)
    __swig_getmethods__["GetAPIVersionMinor"] = lambda x: _ok.okCFrontPanel_GetAPIVersionMinor
    if _newclass:GetAPIVersionMinor = staticmethod(_ok.okCFrontPanel_GetAPIVersionMinor)
    __swig_getmethods__["GetAPIVersionMicro"] = lambda x: _ok.okCFrontPanel_GetAPIVersionMicro
    if _newclass:GetAPIVersionMicro = staticmethod(_ok.okCFrontPanel_GetAPIVersionMicro)
    __swig_getmethods__["GetAPIVersionString"] = lambda x: _ok.okCFrontPanel_GetAPIVersionString
    if _newclass:GetAPIVersionString = staticmethod(_ok.okCFrontPanel_GetAPIVersionString)
    __swig_getmethods__["CheckAPIVersion"] = lambda x: _ok.okCFrontPanel_CheckAPIVersion
    if _newclass:CheckAPIVersion = staticmethod(_ok.okCFrontPanel_CheckAPIVersion)
    brdUnknown = _ok.okCFrontPanel_brdUnknown
    brdXEM3001v1 = _ok.okCFrontPanel_brdXEM3001v1
    brdXEM3001v2 = _ok.okCFrontPanel_brdXEM3001v2
    brdXEM3010 = _ok.okCFrontPanel_brdXEM3010
    brdXEM3005 = _ok.okCFrontPanel_brdXEM3005
    brdXEM3001CL = _ok.okCFrontPanel_brdXEM3001CL
    brdXEM3020 = _ok.okCFrontPanel_brdXEM3020
    brdXEM3050 = _ok.okCFrontPanel_brdXEM3050
    brdXEM9002 = _ok.okCFrontPanel_brdXEM9002
    brdXEM3001RB = _ok.okCFrontPanel_brdXEM3001RB
    brdXEM5010 = _ok.okCFrontPanel_brdXEM5010
    brdXEM6110LX45 = _ok.okCFrontPanel_brdXEM6110LX45
    brdXEM6001 = _ok.okCFrontPanel_brdXEM6001
    brdXEM6010LX45 = _ok.okCFrontPanel_brdXEM6010LX45
    brdXEM6010LX150 = _ok.okCFrontPanel_brdXEM6010LX150
    brdXEM6110LX150 = _ok.okCFrontPanel_brdXEM6110LX150
    brdXEM6006LX9 = _ok.okCFrontPanel_brdXEM6006LX9
    brdXEM6006LX16 = _ok.okCFrontPanel_brdXEM6006LX16
    brdXEM6006LX25 = _ok.okCFrontPanel_brdXEM6006LX25
    brdXEM5010LX110 = _ok.okCFrontPanel_brdXEM5010LX110
    brdZEM4310 = _ok.okCFrontPanel_brdZEM4310
    brdXEM6310LX45 = _ok.okCFrontPanel_brdXEM6310LX45
    brdXEM6310LX150 = _ok.okCFrontPanel_brdXEM6310LX150
    brdXEM6110v2LX45 = _ok.okCFrontPanel_brdXEM6110v2LX45
    brdXEM6110v2LX150 = _ok.okCFrontPanel_brdXEM6110v2LX150
    brdXEM6002LX9 = _ok.okCFrontPanel_brdXEM6002LX9
    brdXEM6310MTLX45T = _ok.okCFrontPanel_brdXEM6310MTLX45T
    brdXEM6320LX130T = _ok.okCFrontPanel_brdXEM6320LX130T
    brdXEM7350K70T = _ok.okCFrontPanel_brdXEM7350K70T
    brdXEM7350K160T = _ok.okCFrontPanel_brdXEM7350K160T
    brdXEM7350K410T = _ok.okCFrontPanel_brdXEM7350K410T
    brdXEM6310MTLX150T = _ok.okCFrontPanel_brdXEM6310MTLX150T
    brdZEM5305A2 = _ok.okCFrontPanel_brdZEM5305A2
    brdZEM5305A7 = _ok.okCFrontPanel_brdZEM5305A7
    brdXEM7001A15 = _ok.okCFrontPanel_brdXEM7001A15
    brdXEM7001A35 = _ok.okCFrontPanel_brdXEM7001A35
    brdXEM7360K160T = _ok.okCFrontPanel_brdXEM7360K160T
    brdXEM7360K410T = _ok.okCFrontPanel_brdXEM7360K410T
    brdZEM5310A4 = _ok.okCFrontPanel_brdZEM5310A4
    brdZEM5310A7 = _ok.okCFrontPanel_brdZEM5310A7
    brdZEM5370A5 = _ok.okCFrontPanel_brdZEM5370A5
    brdXEM7010A50 = _ok.okCFrontPanel_brdXEM7010A50
    brdXEM7010A200 = _ok.okCFrontPanel_brdXEM7010A200
    brdXEM7310A75 = _ok.okCFrontPanel_brdXEM7310A75
    brdXEM7310A200 = _ok.okCFrontPanel_brdXEM7310A200
    brdXEM7320A75T = _ok.okCFrontPanel_brdXEM7320A75T
    brdXEM7320A200T = _ok.okCFrontPanel_brdXEM7320A200T
    brdXEM7305 = _ok.okCFrontPanel_brdXEM7305
    NoError = _ok.okCFrontPanel_NoError
    Failed = _ok.okCFrontPanel_Failed
    Timeout = _ok.okCFrontPanel_Timeout
    DoneNotHigh = _ok.okCFrontPanel_DoneNotHigh
    TransferError = _ok.okCFrontPanel_TransferError
    CommunicationError = _ok.okCFrontPanel_CommunicationError
    InvalidBitstream = _ok.okCFrontPanel_InvalidBitstream
    FileError = _ok.okCFrontPanel_FileError
    DeviceNotOpen = _ok.okCFrontPanel_DeviceNotOpen
    InvalidEndpoint = _ok.okCFrontPanel_InvalidEndpoint
    InvalidBlockSize = _ok.okCFrontPanel_InvalidBlockSize
    I2CRestrictedAddress = _ok.okCFrontPanel_I2CRestrictedAddress
    I2CBitError = _ok.okCFrontPanel_I2CBitError
    I2CNack = _ok.okCFrontPanel_I2CNack
    I2CUnknownStatus = _ok.okCFrontPanel_I2CUnknownStatus
    UnsupportedFeature = _ok.okCFrontPanel_UnsupportedFeature
    FIFOUnderflow = _ok.okCFrontPanel_FIFOUnderflow
    FIFOOverflow = _ok.okCFrontPanel_FIFOOverflow
    DataAlignmentError = _ok.okCFrontPanel_DataAlignmentError
    InvalidResetProfile = _ok.okCFrontPanel_InvalidResetProfile
    InvalidParameter = _ok.okCFrontPanel_InvalidParameter
    def __init__(self): 
        this = _ok.new_okCFrontPanel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_okCFrontPanel
    __del__ = lambda self : None;
    __swig_getmethods__["AddCustomDevice"] = lambda x: _ok.okCFrontPanel_AddCustomDevice
    if _newclass:AddCustomDevice = staticmethod(_ok.okCFrontPanel_AddCustomDevice)
    __swig_getmethods__["RemoveCustomDevice"] = lambda x: _ok.okCFrontPanel_RemoveCustomDevice
    if _newclass:RemoveCustomDevice = staticmethod(_ok.okCFrontPanel_RemoveCustomDevice)
    def ConfigureFPGA(self, *args): return _ok.okCFrontPanel_ConfigureFPGA(self, *args)
    def CreateLuaScriptEngine(self): return _ok.okCFrontPanel_CreateLuaScriptEngine(self)
    def EnableAsynchronousTransfers(self, *args): return _ok.okCFrontPanel_EnableAsynchronousTransfers(self, *args)
    def GetDeviceCount(self): return _ok.okCFrontPanel_GetDeviceCount(self)
    def GetFPGAResetProfile(self, *args): return _ok.okCFrontPanel_GetFPGAResetProfile(self, *args)
    def SetFPGAResetProfile(self, *args): return _ok.okCFrontPanel_SetFPGAResetProfile(self, *args)
    def FlashEraseSector(self, *args): return _ok.okCFrontPanel_FlashEraseSector(self, *args)
    def GetWireInValue(self, *args): return _ok.okCFrontPanel_GetWireInValue(self, *args)
    def ReadRegister(self, *args): return _ok.okCFrontPanel_ReadRegister(self, *args)
    def ReadRegisters(self, *args): return _ok.okCFrontPanel_ReadRegisters(self, *args)
    def WriteRegister(self, *args): return _ok.okCFrontPanel_WriteRegister(self, *args)
    def WriteRegisters(self, *args): return _ok.okCFrontPanel_WriteRegisters(self, *args)
    def GetDeviceID(self): return _ok.okCFrontPanel_GetDeviceID(self)
    def GetDeviceListModel(self, *args): return _ok.okCFrontPanel_GetDeviceListModel(self, *args)
    def GetDeviceListSerial(self, *args): return _ok.okCFrontPanel_GetDeviceListSerial(self, *args)
    def GetDeviceMajorVersion(self): return _ok.okCFrontPanel_GetDeviceMajorVersion(self)
    def GetDeviceMinorVersion(self): return _ok.okCFrontPanel_GetDeviceMinorVersion(self)
    def GetDeviceSensors(self): return _ok.okCFrontPanel_GetDeviceSensors(self)
    def GetDeviceSettings(self, *args): return _ok.okCFrontPanel_GetDeviceSettings(self, *args)
    def GetEepromPLL22150Configuration(self, *args): return _ok.okCFrontPanel_GetEepromPLL22150Configuration(self, *args)
    def GetEepromPLL22393Configuration(self, *args): return _ok.okCFrontPanel_GetEepromPLL22393Configuration(self, *args)
    def GetPLL22150Configuration(self, *args): return _ok.okCFrontPanel_GetPLL22150Configuration(self, *args)
    def GetPLL22393Configuration(self, *args): return _ok.okCFrontPanel_GetPLL22393Configuration(self, *args)
    def GetSerialNumber(self): return _ok.okCFrontPanel_GetSerialNumber(self)
    def GetHostInterfaceWidth(self): return _ok.okCFrontPanel_GetHostInterfaceWidth(self)
    def IsHighSpeed(self): return _ok.okCFrontPanel_IsHighSpeed(self)
    def IsFrontPanel3Supported(self): return _ok.okCFrontPanel_IsFrontPanel3Supported(self)
    def IsFrontPanelEnabled(self): return _ok.okCFrontPanel_IsFrontPanelEnabled(self)
    def IsOpen(self): return _ok.okCFrontPanel_IsOpen(self)
    def IsRemote(self): return _ok.okCFrontPanel_IsRemote(self)
    def LoadDefaultPLLConfiguration(self): return _ok.okCFrontPanel_LoadDefaultPLLConfiguration(self)
    def OpenBySerial(self, *args): return _ok.okCFrontPanel_OpenBySerial(self, *args)
    def ResetFPGA(self): return _ok.okCFrontPanel_ResetFPGA(self)
    def SetBTPipePollingInterval(self, *args): return _ok.okCFrontPanel_SetBTPipePollingInterval(self, *args)
    def SetDeviceID(self, *args): return _ok.okCFrontPanel_SetDeviceID(self, *args)
    def SetEepromPLL22150Configuration(self, *args): return _ok.okCFrontPanel_SetEepromPLL22150Configuration(self, *args)
    def SetEepromPLL22393Configuration(self, *args): return _ok.okCFrontPanel_SetEepromPLL22393Configuration(self, *args)
    def SetPLL22150Configuration(self, *args): return _ok.okCFrontPanel_SetPLL22150Configuration(self, *args)
    def SetPLL22393Configuration(self, *args): return _ok.okCFrontPanel_SetPLL22393Configuration(self, *args)
    def SetTimeout(self, *args): return _ok.okCFrontPanel_SetTimeout(self, *args)
    __swig_getmethods__["GetErrorString"] = lambda x: _ok.okCFrontPanel_GetErrorString
    if _newclass:GetErrorString = staticmethod(_ok.okCFrontPanel_GetErrorString)
    def GetLastErrorMessage(self): return _ok.okCFrontPanel_GetLastErrorMessage(self)
    def GetDeviceInfo(self, *args): return _ok.okCFrontPanel_GetDeviceInfo(self, *args)
    def GetBoardModel(self): return _ok.okCFrontPanel_GetBoardModel(self)
    __swig_getmethods__["GetBoardModelString"] = lambda x: _ok.okCFrontPanel_GetBoardModelString
    if _newclass:GetBoardModelString = staticmethod(_ok.okCFrontPanel_GetBoardModelString)
    def ActivateTriggerIn(self, *args): return _ok.okCFrontPanel_ActivateTriggerIn(self, *args)
    def IsTriggered(self, *args): return _ok.okCFrontPanel_IsTriggered(self, *args)
    def UpdateTriggerOuts(self): return _ok.okCFrontPanel_UpdateTriggerOuts(self)
    def SetWireInValue(self, *args): return _ok.okCFrontPanel_SetWireInValue(self, *args)
    def UpdateWireIns(self): return _ok.okCFrontPanel_UpdateWireIns(self)
    def GetWireOutValue(self, *args): return _ok.okCFrontPanel_GetWireOutValue(self, *args)
    def UpdateWireOuts(self): return _ok.okCFrontPanel_UpdateWireOuts(self)
    def Close(self): return _ok.okCFrontPanel_Close(self)
    def FlashWrite(self, *args): return _ok.okCFrontPanel_FlashWrite(self, *args)
    def FlashRead(self, *args): return _ok.okCFrontPanel_FlashRead(self, *args)
    def WriteToPipeIn(self, *args): return _ok.okCFrontPanel_WriteToPipeIn(self, *args)
    def ReadFromPipeOut(self, *args): return _ok.okCFrontPanel_ReadFromPipeOut(self, *args)
    def WriteToBlockPipeIn(self, *args): return _ok.okCFrontPanel_WriteToBlockPipeIn(self, *args)
    def ReadFromBlockPipeOut(self, *args): return _ok.okCFrontPanel_ReadFromBlockPipeOut(self, *args)
    def WriteToPipeInThr(self, *args): return _ok.okCFrontPanel_WriteToPipeInThr(self, *args)
    def ReadFromPipeOutThr(self, *args): return _ok.okCFrontPanel_ReadFromPipeOutThr(self, *args)
    def WriteToBlockPipeInThr(self, *args): return _ok.okCFrontPanel_WriteToBlockPipeInThr(self, *args)
    def ReadFromBlockPipeOutThr(self, *args): return _ok.okCFrontPanel_ReadFromBlockPipeOutThr(self, *args)
    def ReadI2C(self, *args): return _ok.okCFrontPanel_ReadI2C(self, *args)
    def WriteI2C(self, *args): return _ok.okCFrontPanel_WriteI2C(self, *args)
okCFrontPanel_swigregister = _ok.okCFrontPanel_swigregister
okCFrontPanel_swigregister(okCFrontPanel)

def okCFrontPanel_GetAPIVersionMajor():
  return _ok.okCFrontPanel_GetAPIVersionMajor()
okCFrontPanel_GetAPIVersionMajor = _ok.okCFrontPanel_GetAPIVersionMajor

def okCFrontPanel_GetAPIVersionMinor():
  return _ok.okCFrontPanel_GetAPIVersionMinor()
okCFrontPanel_GetAPIVersionMinor = _ok.okCFrontPanel_GetAPIVersionMinor

def okCFrontPanel_GetAPIVersionMicro():
  return _ok.okCFrontPanel_GetAPIVersionMicro()
okCFrontPanel_GetAPIVersionMicro = _ok.okCFrontPanel_GetAPIVersionMicro

def okCFrontPanel_GetAPIVersionString():
  return _ok.okCFrontPanel_GetAPIVersionString()
okCFrontPanel_GetAPIVersionString = _ok.okCFrontPanel_GetAPIVersionString

def okCFrontPanel_CheckAPIVersion(*args):
  return _ok.okCFrontPanel_CheckAPIVersion(*args)
okCFrontPanel_CheckAPIVersion = _ok.okCFrontPanel_CheckAPIVersion

def okCFrontPanel_AddCustomDevice(*args):
  return _ok.okCFrontPanel_AddCustomDevice(*args)
okCFrontPanel_AddCustomDevice = _ok.okCFrontPanel_AddCustomDevice

def okCFrontPanel_RemoveCustomDevice(*args):
  return _ok.okCFrontPanel_RemoveCustomDevice(*args)
okCFrontPanel_RemoveCustomDevice = _ok.okCFrontPanel_RemoveCustomDevice

def okCFrontPanel_GetErrorString(*args):
  return _ok.okCFrontPanel_GetErrorString(*args)
okCFrontPanel_GetErrorString = _ok.okCFrontPanel_GetErrorString

def okCFrontPanel_GetBoardModelString(*args):
  return _ok.okCFrontPanel_GetBoardModelString(*args)
okCFrontPanel_GetBoardModelString = _ok.okCFrontPanel_GetBoardModelString

class FrontPanel(okCFrontPanel):
    __swig_setmethods__ = {}
    for _s in [okCFrontPanel]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FrontPanel, name, value)
    __swig_getmethods__ = {}
    for _s in [okCFrontPanel]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FrontPanel, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ok.new_FrontPanel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_FrontPanel
    __del__ = lambda self : None;
FrontPanel_swigregister = _ok.FrontPanel_swigregister
FrontPanel_swigregister(FrontPanel)

class PLL22150(okCPLL22150):
    __swig_setmethods__ = {}
    for _s in [okCPLL22150]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PLL22150, name, value)
    __swig_getmethods__ = {}
    for _s in [okCPLL22150]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PLL22150, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ok.new_PLL22150()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_PLL22150
    __del__ = lambda self : None;
PLL22150_swigregister = _ok.PLL22150_swigregister
PLL22150_swigregister(PLL22150)

class PLL22393(okCPLL22393):
    __swig_setmethods__ = {}
    for _s in [okCPLL22393]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PLL22393, name, value)
    __swig_getmethods__ = {}
    for _s in [okCPLL22393]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PLL22393, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ok.new_PLL22393()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_PLL22393
    __del__ = lambda self : None;
PLL22393_swigregister = _ok.PLL22393_swigregister
PLL22393_swigregister(PLL22393)

class Firmware(okCFirmware):
    __swig_setmethods__ = {}
    for _s in [okCFirmware]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Firmware, name, value)
    __swig_getmethods__ = {}
    for _s in [okCFirmware]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Firmware, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _ok.delete_Firmware
    __del__ = lambda self : None;
Firmware_swigregister = _ok.Firmware_swigregister
Firmware_swigregister(Firmware)

class FirmwarePackage(okCFirmwarePackage):
    __swig_setmethods__ = {}
    for _s in [okCFirmwarePackage]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FirmwarePackage, name, value)
    __swig_getmethods__ = {}
    for _s in [okCFirmwarePackage]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FirmwarePackage, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ok.new_FirmwarePackage()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ok.delete_FirmwarePackage
    __del__ = lambda self : None;
FirmwarePackage_swigregister = _ok.FirmwarePackage_swigregister
FirmwarePackage_swigregister(FirmwarePackage)

class okCFrontPanelDevices(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, okCFrontPanelDevices, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, okCFrontPanelDevices, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ok.new_okCFrontPanelDevices(*args)
        try: self.this.append(this)
        except: self.this = this
    def GetCount(self): return _ok.okCFrontPanelDevices_GetCount(self)
    def GetSerial(self, *args): return _ok.okCFrontPanelDevices_GetSerial(self, *args)
    def Open(self, *args): return _ok.okCFrontPanelDevices_Open(self, *args)
    __swig_destroy__ = _ok.delete_okCFrontPanelDevices
    __del__ = lambda self : None;
okCFrontPanelDevices_swigregister = _ok.okCFrontPanelDevices_swigregister
okCFrontPanelDevices_swigregister(okCFrontPanelDevices)
cvar = _ok.cvar
okREALM_LOCAL = cvar.okREALM_LOCAL
okREALM_TEST = cvar.okREALM_TEST

# This file is compatible with both classic and new-style classes.


