std_msgs/Header header
float64 vehicle_time    #ping time
float64 vehicle_dt1     #time from trigger to center of water track cell
float64 vehicle_dt2     #time from start of output message to center of water track cell
geometry_msgs/Vector3 vehicle_vel
float64 vehicle_figureOfMerit
float64[4] vehicle_beamDistance
float64 vehicle_batteryVoltage
float64 vehicle_speedSound
float64 vehicle_pressure
float64 vehicle_temp